package com.meat.domain;

// Generated Feb 23, 2016 5:30:35 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.*;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "meat_app")
public class Account extends AbstractDomain implements java.io.Serializable {

    private SellerBranch sellerBranch;
    private String entityName;
    private String entityType;
    private BigDecimal amount;

    public Account() {
    }

    public Account(final String id, final SellerBranch sellerBranch, final String entityName, final String entityType,
            final BigDecimal amount) {
        this.id = id;
        this.sellerBranch = sellerBranch;
        this.entityName = entityName;
        this.entityType = entityType;
        this.amount = amount;
    }

    public Account(final String id, final String entityName, final String entityType, final BigDecimal amount) {
        this.id = id;
        this.entityName = entityName;
        this.entityType = entityType;
        this.amount = amount;
    }

    @Column(name = "amount", nullable = false, precision = 7)
    public BigDecimal getAmount() {
        return amount;
    }

    @Column(name = "entity_name", nullable = false, length = 45)
    public String getEntityName() {
        return entityName;
    }

    @Column(name = "entity_type", nullable = false, length = 45)
    public String getEntityType() {
        return entityType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_branch_id")
    public SellerBranch getSellerBranch() {
        return sellerBranch;
    }

    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    public void setEntityName(final String entityName) {
        this.entityName = entityName;
    }

    public void setEntityType(final String entityType) {
        this.entityType = entityType;
    }

    public void setSellerBranch(final SellerBranch sellerBranch) {
        this.sellerBranch = sellerBranch;
    }

}
