package com.meat.domain;

// Generated Nov 10, 2015 12:07:23 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * AmountType generated by hbm2java
 */
@Entity
@Table(name = "amount_type", catalog = "meat_app")
public class AmountType extends AbstractDomain implements java.io.Serializable {

    private int amountTypeName;
    private String amountDescription;
    private Set<Coupon> coupons = new HashSet<Coupon>(0);
    private Set<SellerBranchTax> sellerBranchTaxes = new HashSet<SellerBranchTax>(0);

    public AmountType() {
    }

    public AmountType(final String id, final int amountTypeName) {
        this.id = id;
        this.amountTypeName = amountTypeName;
    }

    public AmountType(final String id, final int amountTypeName, final String amountDescription, final Set<Coupon> coupons,
            final Set<SellerBranchTax> sellerBranchTaxes) {
        this.id = id;
        this.amountTypeName = amountTypeName;
        this.amountDescription = amountDescription;
        this.coupons = coupons;
        this.sellerBranchTaxes = sellerBranchTaxes;
    }

    @Column(name = "amount_description", length = 100)
    public String getAmountDescription() {
        return amountDescription;
    }

    @Column(name = "amount_type_name", nullable = false)
    public int getAmountTypeName() {
        return amountTypeName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "amountType")
    public Set<Coupon> getCoupons() {
        return coupons;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "amountType")
    public Set<SellerBranchTax> getSellerBranchTaxes() {
        return sellerBranchTaxes;
    }

    public void setAmountDescription(final String amountDescription) {
        this.amountDescription = amountDescription;
    }

    public void setAmountTypeName(final int amountTypeName) {
        this.amountTypeName = amountTypeName;
    }

    public void setCoupons(final Set<Coupon> coupons) {
        this.coupons = coupons;
    }

    public void setSellerBranchTaxes(final Set<SellerBranchTax> sellerBranchTaxes) {
        this.sellerBranchTaxes = sellerBranchTaxes;
    }

}
