package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Attributes generated by hbm2java
 */
@Entity
@Table(name = "attributes", catalog = "meat_app")
public class Attributes extends AbstractDomain implements java.io.Serializable {

    private Seo seo;
    private String attributeName;
    private String description;
    private String status;
    private Date attributeCreatedDate;
    private Set<CategoryAttributes> categoryAttributeses = new HashSet<CategoryAttributes>(0);
    private Set<ItemAttributes> itemAttributeses = new HashSet<ItemAttributes>(0);
    private Set<SubCategoryAttributes> subCategoryAttributeses = new HashSet<SubCategoryAttributes>(0);

    public Attributes() {
    }

    public Attributes(final String id, final Seo seo, final String attributeName, final String status, final Date attributeCreatedDate) {
        this.id = id;
        this.seo = seo;
        this.attributeName = attributeName;
        this.status = status;
        this.attributeCreatedDate = attributeCreatedDate;
    }

    public Attributes(final String id, final Seo seo, final String attributeName, final String description, final String status,
            final Date attributeCreatedDate, final Set<CategoryAttributes> categoryAttributeses, final Set<ItemAttributes> itemAttributeses,
            final Set<SubCategoryAttributes> subCategoryAttributeses) {
        this.id = id;
        this.seo = seo;
        this.attributeName = attributeName;
        this.description = description;
        this.status = status;
        this.attributeCreatedDate = attributeCreatedDate;
        this.categoryAttributeses = categoryAttributeses;
        this.itemAttributeses = itemAttributeses;
        this.subCategoryAttributeses = subCategoryAttributeses;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "attribute_created_date", nullable = false, length = 19)
    public Date getAttributeCreatedDate() {
        return attributeCreatedDate;
    }

    @Column(name = "attribute_name", nullable = false, length = 45)
    public String getAttributeName() {
        return attributeName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "attributes")
    public Set<CategoryAttributes> getCategoryAttributeses() {
        return categoryAttributeses;
    }

    @Column(name = "description", length = 45)
    public String getDescription() {
        return description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "attributes")
    public Set<ItemAttributes> getItemAttributeses() {
        return itemAttributeses;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seo_id", nullable = false)
    public Seo getSeo() {
        return seo;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "attributes")
    public Set<SubCategoryAttributes> getSubCategoryAttributeses() {
        return subCategoryAttributeses;
    }

    public void setAttributeCreatedDate(final Date attributeCreatedDate) {
        this.attributeCreatedDate = attributeCreatedDate;
    }

    public void setAttributeName(final String attributeName) {
        this.attributeName = attributeName;
    }

    public void setCategoryAttributeses(final Set<CategoryAttributes> categoryAttributeses) {
        this.categoryAttributeses = categoryAttributeses;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setItemAttributeses(final Set<ItemAttributes> itemAttributeses) {
        this.itemAttributeses = itemAttributeses;
    }

    public void setSeo(final Seo seo) {
        this.seo = seo;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    public void setSubCategoryAttributeses(final Set<SubCategoryAttributes> subCategoryAttributeses) {
        this.subCategoryAttributeses = subCategoryAttributeses;
    }

}
