package com.meat.domain;

// Generated Feb 13, 2016 10:49:53 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * BankOffer generated by hbm2java
 */
@Entity
@Table(name = "bank_offer", catalog = "meat_app")
public class BankOffer extends AbstractDomain implements java.io.Serializable {

    private Offer offer;
    private String bankName;
    private String status;
    private Set<OfferConfig> offerConfigs = new HashSet<OfferConfig>(0);

    public BankOffer() {
    }

    public BankOffer(final String id, final Offer offer, final String bankName, final String status) {
        this.id = id;
        this.offer = offer;
        this.bankName = bankName;
        this.status = status;
    }

    public BankOffer(final String id, final Offer offer, final String bankName, final String status, final Set<OfferConfig> offerConfigs) {
        this.id = id;
        this.offer = offer;
        this.bankName = bankName;
        this.status = status;
        this.offerConfigs = offerConfigs;
    }

    @Column(name = "bank_name", nullable = false, length = 45)
    public String getBankName() {
        return bankName;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "offer_id", nullable = false)
    public Offer getOffer() {
        return offer;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bankOffer")
    public Set<OfferConfig> getOfferConfigs() {
        return offerConfigs;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setBankName(final String bankName) {
        this.bankName = bankName;
    }

    public void setOffer(final Offer offer) {
        this.offer = offer;
    }

    public void setOfferConfigs(final Set<OfferConfig> offerConfigs) {
        this.offerConfigs = offerConfigs;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
