package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * CategoryCriteria generated by hbm2java
 */
@Entity
@Table(name = "category_criteria", catalog = "meat_app")
public class CategoryCriteria extends AbstractDomain implements java.io.Serializable {

    private Criteria criteria;
    private Category category;
    private String criteriaValue;
    private String status;

    public CategoryCriteria() {
    }

    public CategoryCriteria(final String id, final Criteria criteria, final Category category, final String criteriaValue,
            final String status) {
        this.id = id;
        this.criteria = criteria;
        this.category = category;
        this.criteriaValue = criteriaValue;
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    public Category getCategory() {
        return category;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "criteria_id", nullable = false)
    public Criteria getCriteria() {
        return criteria;
    }

    @Column(name = "criteria_value", nullable = false, length = 10)
    public String getCriteriaValue() {
        return criteriaValue;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setCategory(final Category category) {
        this.category = category;
    }

    public void setCriteria(final Criteria criteria) {
        this.criteria = criteria;
    }

    public void setCriteriaValue(final String criteriaValue) {
        this.criteriaValue = criteriaValue;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
