package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * CategoryImages generated by hbm2java
 */
@Entity
@Table(name = "category_images", catalog = "meat_app")
public class CategoryImages extends AbstractDomain implements java.io.Serializable {

    private Category category;
    private String imageName;
    private String imageType;
    private String imageLocation;

    public CategoryImages() {
    }

    public CategoryImages(final String id, final Category category, final String imageName, final String imageType,
            final String imageLocation) {
        this.id = id;
        this.category = category;
        this.imageName = imageName;
        this.imageType = imageType;
        this.imageLocation = imageLocation;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    public Category getCategory() {
        return category;
    }

    @Column(name = "image_location", nullable = false, length = 100)
    public String getImageLocation() {
        return imageLocation;
    }

    @Column(name = "image_name", nullable = false, length = 45)
    public String getImageName() {
        return imageName;
    }

    @Column(name = "image_type", nullable = false, length = 45)
    public String getImageType() {
        return imageType;
    }

    public void setCategory(final Category category) {
        this.category = category;
    }

    public void setImageLocation(final String imageLocation) {
        this.imageLocation = imageLocation;
    }

    public void setImageName(final String imageName) {
        this.imageName = imageName;
    }

    public void setImageType(final String imageType) {
        this.imageType = imageType;
    }

}
