package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * CategoryAttributes generated by hbm2java
 */
@Entity
@Table(name = "category_attributes", catalog = "meat_app")
public class CategoryAttributes extends AbstractDomain implements java.io.Serializable {

    private Attributes attributes;
    private Category category;
    private String attributeValue;
    private String status;
    private String searchableStatus;
    private Set<ItemAttributes> itemAttributeses = new HashSet<ItemAttributes>(0);

    public CategoryAttributes() {
    }

    public CategoryAttributes(final String id, final Attributes attributes, final Category category, final String attributeValue,
            final String status) {
        this.id = id;
        this.attributes = attributes;
        this.category = category;
        this.attributeValue = attributeValue;
        this.status = status;
    }

    public CategoryAttributes(final String id, final Attributes attributes, final String searchableStatus, final Category category,
            final String attributeValue, final String status, final Set<ItemAttributes> itemAttributeses) {
        this.id = id;
        this.attributes = attributes;
        this.category = category;
        this.attributeValue = attributeValue;
        this.searchableStatus = searchableStatus;
        this.itemAttributeses = itemAttributeses;
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "attributes_id", nullable = false)
    public Attributes getAttributes() {
        return attributes;
    }

    @Column(name = "attribute_value", nullable = false, length = 100)
    public String getAttributeValue() {
        return attributeValue;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    public Category getCategory() {
        return category;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryAttributes")
    public Set<ItemAttributes> getItemAttributeses() {
        return itemAttributeses;
    }

    @Column(name = "searchable_status")
    public String getSearchableStatus() {
        return searchableStatus;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setAttributes(final Attributes attributes) {
        this.attributes = attributes;
    }

    public void setAttributeValue(final String attributeValue) {
        this.attributeValue = attributeValue;
    }

    public void setCategory(final Category category) {
        this.category = category;
    }

    public void setItemAttributeses(final Set<ItemAttributes> itemAttributeses) {
        this.itemAttributeses = itemAttributeses;
    }

    public void setSearchableStatus(final String searchableStatus) {
        this.searchableStatus = searchableStatus;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
