package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * CouponBuyXGetY generated by hbm2java
 */
@Entity
@Table(name = "coupon_buy_x_get_y", catalog = "meat_app")
public class CouponBuyXGetY extends AbstractDomain implements java.io.Serializable {

    private Coupon coupon;
    private int buyX;
    private int getY;
    private String purchaseItemId;
    private String discountItemId;
    private String status;

    public CouponBuyXGetY() {
    }

    public CouponBuyXGetY(final String id, final Coupon coupon, final int buyX, final int getY, final String purchaseItemId,
            final String discountItemId, final String status) {
        this.id = id;
        this.coupon = coupon;
        this.buyX = buyX;
        this.getY = getY;
        this.purchaseItemId = purchaseItemId;
        this.discountItemId = discountItemId;
        this.status = status;
    }

    @Column(name = "buy_x", nullable = false)
    public int getBuyX() {
        return buyX;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "coupon_id", nullable = false)
    public Coupon getCoupon() {
        return coupon;
    }

    @Column(name = "discount_item_id", nullable = false, length = 100)
    public String getDiscountItemId() {
        return discountItemId;
    }

    @Column(name = "get_y", nullable = false)
    public int getGetY() {
        return getY;
    }

    @Column(name = "purchase_item_id", nullable = false, length = 100)
    public String getPurchaseItemId() {
        return purchaseItemId;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setBuyX(final int buyX) {
        this.buyX = buyX;
    }

    public void setCoupon(final Coupon coupon) {
        this.coupon = coupon;
    }

    public void setDiscountItemId(final String discountItemId) {
        this.discountItemId = discountItemId;
    }

    public void setGetY(final int getY) {
        this.getY = getY;
    }

    public void setPurchaseItemId(final String purchaseItemId) {
        this.purchaseItemId = purchaseItemId;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
