package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "coupon", catalog = "meat_app")
public class Coupon extends AbstractDomain implements java.io.Serializable {
    private AmountType amountType;
    private String couponName;
    private String description;
    private String status;
    private String couponCode;
    private String placedByStatus;
    private Date couponFromDate;
    private Date couponToDate;
    private Integer quantity;
    private BigDecimal invoiceAmount;
    private String billType;
    private String couponType;
    private long couponCount;
    private Date createdDate;
    private int amountTypeValue;
    private Set<CouponPercentDirect> couponPercentDirects = new HashSet<CouponPercentDirect>(0);
    private Set<CouponBuyXGetY> couponBuyXGetYs = new HashSet<CouponBuyXGetY>(0);

    public Coupon() {
    }

    public Coupon(final String id, final AmountType amountType, final String couponName, final String status, final String couponCode,
            final String placedByStatus, final Date couponFromDate, final Date couponToDate, final long couponCount,
            final int amountTypeValue) {
        this.id = id;
        this.amountType = amountType;
        this.couponName = couponName;
        this.status = status;
        this.couponCode = couponCode;
        this.placedByStatus = placedByStatus;
        this.couponFromDate = couponFromDate;
        this.couponToDate = couponToDate;
        this.couponCount = couponCount;
        this.amountTypeValue = amountTypeValue;
    }

    public Coupon(final String id, final AmountType amountType, final String couponName, final String description, final String status,
            final String couponCode, final String placedByStatus, final Date couponFromDate, final Date couponToDate,
            final Integer quantity, final BigDecimal invoiceAmount, final String billType, final String couponType, final long couponCount,
            final Date createdDate, final int amountTypeValue, final Set<CouponPercentDirect> couponPercentDirects,
            final Set<CouponBuyXGetY> couponBuyXGetYs) {
        this.id = id;
        this.amountType = amountType;
        this.couponName = couponName;
        this.description = description;
        this.status = status;
        this.couponCode = couponCode;
        this.placedByStatus = placedByStatus;
        this.couponFromDate = couponFromDate;
        this.couponToDate = couponToDate;
        this.quantity = quantity;
        this.invoiceAmount = invoiceAmount;
        this.billType = billType;
        this.couponType = couponType;
        this.couponCount = couponCount;
        this.createdDate = createdDate;
        this.amountTypeValue = amountTypeValue;
        this.couponPercentDirects = couponPercentDirects;
        this.couponBuyXGetYs = couponBuyXGetYs;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "amount_type_id", nullable = false)
    public AmountType getAmountType() {
        return amountType;
    }

    @Column(name = "amount_type_value", nullable = false)
    public int getAmountTypeValue() {
        return amountTypeValue;
    }

    @Column(name = "bill_type", length = 45)
    public String getBillType() {
        return billType;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "coupon")
    public Set<CouponBuyXGetY> getCouponBuyXGetYs() {
        return couponBuyXGetYs;
    }

    @Column(name = "coupon_code", nullable = false, length = 45)
    public String getCouponCode() {
        return couponCode;
    }

    @Column(name = "coupon_count", nullable = false)
    public long getCouponCount() {
        return couponCount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "coupon_from_date", nullable = false, length = 10)
    public Date getCouponFromDate() {
        return couponFromDate;
    }

    @Column(name = "coupon_name", nullable = false, length = 45)
    public String getCouponName() {
        return couponName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "coupon")
    public Set<CouponPercentDirect> getCouponPercentDirects() {
        return couponPercentDirects;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "coupon_to_date", nullable = false, length = 10)
    public Date getCouponToDate() {
        return couponToDate;
    }

    @Column(name = "coupon_type", length = 45)
    public String getCouponType() {
        return couponType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "description", length = 45)
    public String getDescription() {
        return description;
    }

    @Column(name = "invoice_amount", precision = 7)
    public BigDecimal getInvoiceAmount() {
        return invoiceAmount;
    }

    @Column(name = "placed_by_status", nullable = false, length = 45)
    public String getPlacedByStatus() {
        return placedByStatus;
    }

    @Column(name = "quantity")
    public Integer getQuantity() {
        return quantity;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setAmountType(final AmountType amountType) {
        this.amountType = amountType;
    }

    public void setAmountTypeValue(final int amountTypeValue) {
        this.amountTypeValue = amountTypeValue;
    }

    public void setBillType(final String billType) {
        this.billType = billType;
    }

    public void setCouponBuyXGetYs(final Set<CouponBuyXGetY> couponBuyXGetYs) {
        this.couponBuyXGetYs = couponBuyXGetYs;
    }

    public void setCouponCode(final String couponCode) {
        this.couponCode = couponCode;
    }

    public void setCouponCount(final long couponCount) {
        this.couponCount = couponCount;
    }

    public void setCouponFromDate(final Date couponFromDate) {
        this.couponFromDate = couponFromDate;
    }

    public void setCouponName(final String couponName) {
        this.couponName = couponName;
    }

    public void setCouponPercentDirects(final Set<CouponPercentDirect> couponPercentDirects) {
        this.couponPercentDirects = couponPercentDirects;
    }

    public void setCouponToDate(final Date couponToDate) {
        this.couponToDate = couponToDate;
    }

    public void setCouponType(final String couponType) {
        this.couponType = couponType;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setInvoiceAmount(final BigDecimal invoiceAmount) {
        this.invoiceAmount = invoiceAmount;
    }

    public void setPlacedByStatus(final String placedByStatus) {
        this.placedByStatus = placedByStatus;
    }

    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
