package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.*;

/**
 * CouponPercentDirect generated by hbm2java
 */
@Entity
@Table(name = "coupon_percent_direct", catalog = "meat_app")
public class CouponPercentDirect extends AbstractDomain implements java.io.Serializable {

    private Coupon coupon;
    private Integer discountPercent;
    private BigDecimal discountAmount;

    public CouponPercentDirect() {
    }

    public CouponPercentDirect(final String id, final Coupon coupon) {
        this.id = id;
        this.coupon = coupon;
    }

    public CouponPercentDirect(final String id, final Coupon coupon, final Integer discountPercent, final BigDecimal discountAmount) {
        this.id = id;
        this.coupon = coupon;
        this.discountPercent = discountPercent;
        this.discountAmount = discountAmount;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "coupon_id", nullable = false)
    public Coupon getCoupon() {
        return coupon;
    }

    @Column(name = "discount_amount", precision = 7)
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    @Column(name = "discount_percent")
    public Integer getDiscountPercent() {
        return discountPercent;
    }

    public void setCoupon(final Coupon coupon) {
        this.coupon = coupon;
    }

    public void setDiscountAmount(final BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    public void setDiscountPercent(final Integer discountPercent) {
        this.discountPercent = discountPercent;
    }

}
