package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Criteria generated by hbm2java
 */
@Entity
@Table(name = "criteria", catalog = "meat_app")
public class Criteria extends AbstractDomain implements java.io.Serializable {

    private Seo seo;
    private String criteriaName;
    private Integer orderOfPlace;
    private String description;
    private Date createdDate;
    private String status;
    private Set<CategoryCriteria> categoryCriterias = new HashSet<CategoryCriteria>(0);
    private Set<SellerItemCriteria> sellerItemCriterias = new HashSet<SellerItemCriteria>(0);

    public Criteria() {
    }

    public Criteria(final String id, final Seo seo, final String criteriaName, final Integer orderOfPlace, final String description,
            final Date createdDate, final String status, final Set<CategoryCriteria> categoryCriterias,
            final Set<SellerItemCriteria> sellerItemCriterias) {
        this.id = id;
        this.seo = seo;
        this.criteriaName = criteriaName;
        this.orderOfPlace = orderOfPlace;
        this.description = description;
        this.createdDate = createdDate;
        this.status = status;
        this.categoryCriterias = categoryCriterias;
        this.sellerItemCriterias = sellerItemCriterias;
    }

    public Criteria(final String id, final String criteriaName, final Date createdDate, final String status) {
        this.id = id;
        this.criteriaName = criteriaName;
        this.createdDate = createdDate;
        this.status = status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "criteria")
    public Set<CategoryCriteria> getCategoryCriterias() {
        return categoryCriterias;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", nullable = false, length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "criteria_name", nullable = false, length = 45)
    public String getCriteriaName() {
        return criteriaName;
    }

    @Column(name = "description", length = 800)
    public String getDescription() {
        return description;
    }

    @Column(name = "order_of_place")
    public Integer getOrderOfPlace() {
        return orderOfPlace;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "criteria")
    public Set<SellerItemCriteria> getSellerItemCriterias() {
        return sellerItemCriterias;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seo_id")
    public Seo getSeo() {
        return seo;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setCategoryCriterias(final Set<CategoryCriteria> categoryCriterias) {
        this.categoryCriterias = categoryCriterias;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setCriteriaName(final String criteriaName) {
        this.criteriaName = criteriaName;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setOrderOfPlace(final Integer orderOfPlace) {
        this.orderOfPlace = orderOfPlace;
    }

    public void setSellerItemCriterias(final Set<SellerItemCriteria> sellerItemCriterias) {
        this.sellerItemCriterias = sellerItemCriterias;
    }

    public void setSeo(final Seo seo) {
        this.seo = seo;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
