package com.meat.domain;

// Generated Feb 3, 2016 5:02:39 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.*;

/**
 * InvoiceStatusCodes generated by hbm2java
 */
@Entity
@Table(name = "invoice_status_codes", catalog = "meat_app")
public class InvoiceStatusCodes extends AbstractDomain implements java.io.Serializable {

    private Invoice invoice;
    private String invoiceStatusCode;
    private String invoiceStatusDescription;
    private Date invoiceStatusDate;

    public InvoiceStatusCodes() {
    }

    public InvoiceStatusCodes(final String id, final Invoice invoice, final String invoiceStatusCode, final Date invoiceStatusDate) {
        this.id = id;
        this.invoice = invoice;
        this.invoiceStatusCode = invoiceStatusCode;
        this.invoiceStatusDate = invoiceStatusDate;
    }

    public InvoiceStatusCodes(final String id, final Invoice invoice, final String invoiceStatusCode, final String invoiceStatusDescription,
            final Date invoiceStatusDate) {
        this.id = id;
        this.invoice = invoice;
        this.invoiceStatusCode = invoiceStatusCode;
        this.invoiceStatusDescription = invoiceStatusDescription;
        this.invoiceStatusDate = invoiceStatusDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "invoice_id", nullable = false)
    public Invoice getInvoice() {
        return invoice;
    }

    @Column(name = "invoice_status_code", nullable = false, length = 45)
    public String getInvoiceStatusCode() {
        return invoiceStatusCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "invoice_status_date", nullable = false, length = 19)
    public Date getInvoiceStatusDate() {
        return invoiceStatusDate;
    }

    @Column(name = "invoice_status_description", length = 100)
    public String getInvoiceStatusDescription() {
        return invoiceStatusDescription;
    }

    public void setInvoice(final Invoice invoice) {
        this.invoice = invoice;
    }

    public void setInvoiceStatusCode(final String invoiceStatusCode) {
        this.invoiceStatusCode = invoiceStatusCode;
    }

    public void setInvoiceStatusDate(final Date invoiceStatusDate) {
        this.invoiceStatusDate = invoiceStatusDate;
    }

    public void setInvoiceStatusDescription(final String invoiceStatusDescription) {
        this.invoiceStatusDescription = invoiceStatusDescription;
    }

}
