package com.meat.domain;

// Generated Feb 3, 2016 5:02:39 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * InvoiceTransaction generated by hbm2java
 */
@Entity
@Table(name = "invoice_transaction", catalog = "meat_app")
public class InvoiceTransaction extends AbstractDomain implements java.io.Serializable {

    private SellerInvoice sellerInvoice;
    private MeatInvoice meatInvoice;
    private String transactionType;
    private String receiptNo;
    private String referenceDocumentNo;
    private Date date;
    private BigDecimal amount;
    private String transactionCode;

    public InvoiceTransaction() {
    }

    public InvoiceTransaction(final String id, final Date date, final BigDecimal amount) {
        this.id = id;
        this.date = date;
        this.amount = amount;
    }

    public InvoiceTransaction(final String id, final SellerInvoice sellerInvoice, final MeatInvoice meatInvoice,
            final String transactionType, final String receiptNo, final String referenceDocumentNo, final Date date,
            final BigDecimal amount, final String transactionCode) {
        this.id = id;
        this.sellerInvoice = sellerInvoice;
        this.meatInvoice = meatInvoice;
        this.transactionType = transactionType;
        this.receiptNo = receiptNo;
        this.referenceDocumentNo = referenceDocumentNo;
        this.date = date;
        this.amount = amount;
        this.transactionCode = transactionCode;
    }

    @Column(name = "amount", nullable = false, precision = 20, scale = 10)
    public BigDecimal getAmount() {
        return amount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date", nullable = false, length = 19)
    public Date getDate() {
        return date;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "meat_invoice_id")
    public MeatInvoice getMeatInvoice() {
        return meatInvoice;
    }

    @Column(name = "receipt_no", length = 45)
    public String getReceiptNo() {
        return receiptNo;
    }

    @Column(name = "reference_document_no", length = 45)
    public String getReferenceDocumentNo() {
        return referenceDocumentNo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_invoice_id")
    public SellerInvoice getSellerInvoice() {
        return sellerInvoice;
    }

    @Column(name = "transaction_code", length = 100)
    public String getTransactionCode() {
        return transactionCode;
    }

    @Column(name = "transaction_type", length = 45)
    public String getTransactionType() {
        return transactionType;
    }

    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    public void setDate(final Date date) {
        this.date = date;
    }

    public void setMeatInvoice(final MeatInvoice meatInvoice) {
        this.meatInvoice = meatInvoice;
    }

    public void setReceiptNo(final String receiptNo) {
        this.receiptNo = receiptNo;
    }

    public void setReferenceDocumentNo(final String referenceDocumentNo) {
        this.referenceDocumentNo = referenceDocumentNo;
    }

    public void setSellerInvoice(final SellerInvoice sellerInvoice) {
        this.sellerInvoice = sellerInvoice;
    }

    public void setTransactionCode(final String transactionCode) {
        this.transactionCode = transactionCode;
    }

    public void setTransactionType(final String transactionType) {
        this.transactionType = transactionType;
    }

}
