package com.meat.domain;

// Generated Feb 3, 2016 5:02:39 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice", catalog = "meat_app")
public class Invoice extends AbstractDomain implements java.io.Serializable {

    private Orders orders;
    private String invoiceOrder;
    private Date invoiceDate;
    private String invoiceDetails;
    private Set<InvoiceStatusCodes> invoiceStatusCodeses = new HashSet<InvoiceStatusCodes>(0);

    public Invoice() {
    }

    public Invoice(final String id, final Orders orders, final String invoiceOrder, final Date invoiceDate) {
        this.id = id;
        this.orders = orders;
        this.invoiceOrder = invoiceOrder;
        this.invoiceDate = invoiceDate;
    }

    public Invoice(final String id, final Orders orders, final String invoiceOrder, final Date invoiceDate, final String invoiceDetails,
            final Set<InvoiceStatusCodes> invoiceStatusCodeses) {
        this.id = id;
        this.orders = orders;
        this.invoiceOrder = invoiceOrder;
        this.invoiceDate = invoiceDate;
        this.invoiceDetails = invoiceDetails;
        this.invoiceStatusCodeses = invoiceStatusCodeses;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "invoice_date", nullable = false, length = 19)
    public Date getInvoiceDate() {
        return invoiceDate;
    }

    @Column(name = "invoice_details", length = 500)
    public String getInvoiceDetails() {
        return invoiceDetails;
    }

    @Column(name = "invoice_order", nullable = false, length = 45)
    public String getInvoiceOrder() {
        return invoiceOrder;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
    public Set<InvoiceStatusCodes> getInvoiceStatusCodeses() {
        return invoiceStatusCodeses;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "orders_id", nullable = false)
    public Orders getOrders() {
        return orders;
    }

    public void setInvoiceDate(final Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    public void setInvoiceDetails(final String invoiceDetails) {
        this.invoiceDetails = invoiceDetails;
    }

    public void setInvoiceOrder(final String invoiceOrder) {
        this.invoiceOrder = invoiceOrder;
    }

    public void setInvoiceStatusCodeses(final Set<InvoiceStatusCodes> invoiceStatusCodeses) {
        this.invoiceStatusCodeses = invoiceStatusCodeses;
    }

    public void setOrders(final Orders orders) {
        this.orders = orders;
    }

}
