package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", catalog = "meat_app")
public class Item extends AbstractDomain implements java.io.Serializable {

    private Seo seo;
    private SubCategory subCategory;
    private String itemName;
    private String sellingTag;
    private Date createdDate;
    private String meatStatus;
    private String description;
    private String status;
    private String itemCode;
    private Integer countFlag;
    private long itemCount;
    private Set<UserItemRating> userItemRatings = new HashSet<UserItemRating>(0);
    private Set<ItemAttributes> itemAttributeses = new HashSet<ItemAttributes>(0);
    private Set<UserWishList> userWishLists = new HashSet<UserWishList>(0);
    private Set<ItemImages> itemImageses = new HashSet<ItemImages>(0);
    private Set<ItemTags> itemTagses = new HashSet<ItemTags>(0);
    private Set<SellerItem> sellerItems = new HashSet<SellerItem>(0);

    public Item() {
    }

    public Item(final String id, final Seo seo, final SubCategory subCategory, final String itemName, final Date createdDate,
            final String description, final String status, final Integer countFlag, final String itemCode, final long itemCount) {
        this.id = id;
        this.seo = seo;
        this.subCategory = subCategory;
        this.itemName = itemName;
        this.createdDate = createdDate;
        this.description = description;
        this.countFlag = countFlag;
        this.status = status;
        this.itemCode = itemCode;
        this.itemCount = itemCount;
    }

    public Item(final String id, final Seo seo, final SubCategory subCategory, final String itemName, final String sellingTag,
            final Date createdDate, final String meatStatus, final String description, final String status, final String itemCode,
            final long itemCount, final Set<UserItemRating> userItemRatings, final Integer countFlag,
            final Set<ItemAttributes> itemAttributeses, final Set<UserWishList> userWishLists, final Set<ItemImages> itemImageses,
            final Set<ItemTags> itemTagses, final Set<SellerItem> sellerItems) {
        this.id = id;
        this.seo = seo;
        this.subCategory = subCategory;
        this.itemName = itemName;
        this.sellingTag = sellingTag;
        this.createdDate = createdDate;
        this.meatStatus = meatStatus;
        this.description = description;
        this.status = status;
        this.countFlag = countFlag;
        this.itemCode = itemCode;
        this.itemCount = itemCount;
        this.userItemRatings = userItemRatings;
        this.itemAttributeses = itemAttributeses;
        this.userWishLists = userWishLists;
        this.itemImageses = itemImageses;
        this.itemTagses = itemTagses;
        this.sellerItems = sellerItems;
    }

    @Column(name = "count_flag")
    public Integer getCountFlag() {
        return countFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", nullable = false, length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "description", nullable = false, length = 2000)
    public String getDescription() {
        return description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<ItemAttributes> getItemAttributeses() {
        return itemAttributeses;
    }

    @Column(name = "item_code", nullable = false, length = 45)
    public String getItemCode() {
        return itemCode;
    }

    @Column(name = "item_count", nullable = false)
    public long getItemCount() {
        return itemCount;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<ItemImages> getItemImageses() {
        return itemImageses;
    }

    @Column(name = "item_name", nullable = false, length = 45)
    public String getItemName() {
        return itemName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<ItemTags> getItemTagses() {
        return itemTagses;
    }

    @Column(name = "meat_status", length = 45)
    public String getMeatStatus() {
        return meatStatus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<SellerItem> getSellerItems() {
        return sellerItems;
    }

    @Column(name = "selling_tag")
    public String getSellingTag() {
        return sellingTag;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seo_id", nullable = false)
    public Seo getSeo() {
        return seo;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sub_category_id", nullable = false)
    public SubCategory getSubCategory() {
        return subCategory;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<UserItemRating> getUserItemRatings() {
        return userItemRatings;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<UserWishList> getUserWishLists() {
        return userWishLists;
    }

    public void setCountFlag(final Integer countFlag) {
        this.countFlag = countFlag;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setItemAttributeses(final Set<ItemAttributes> itemAttributeses) {
        this.itemAttributeses = itemAttributeses;
    }

    public void setItemCode(final String itemCode) {
        this.itemCode = itemCode;
    }

    public void setItemCount(final long itemCount) {
        this.itemCount = itemCount;
    }

    public void setItemImageses(final Set<ItemImages> itemImageses) {
        this.itemImageses = itemImageses;
    }

    public void setItemName(final String itemName) {
        this.itemName = itemName;
    }

    public void setItemTagses(final Set<ItemTags> itemTagses) {
        this.itemTagses = itemTagses;
    }

    public void setMeatStatus(final String meatStatus) {
        this.meatStatus = meatStatus;
    }

    public void setSellerItems(final Set<SellerItem> sellerItems) {
        this.sellerItems = sellerItems;
    }

    public void setSellingTag(final String sellingTag) {
        this.sellingTag = sellingTag;
    }

    public void setSeo(final Seo seo) {
        this.seo = seo;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    public void setSubCategory(final SubCategory subCategory) {
        this.subCategory = subCategory;
    }

    public void setUserItemRatings(final Set<UserItemRating> userSellerItemRatings) {
        userItemRatings = userItemRatings;
    }

    public void setUserWishLists(final Set<UserWishList> userWishLists) {
        this.userWishLists = userWishLists;
    }

}
