package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * ItemTags generated by hbm2java
 */
@Entity
@Table(name = "item_tags", catalog = "meat_app")
public class ItemTags extends AbstractDomain implements java.io.Serializable {

    private Tags tags;
    private Item item;
    private String itemTagsStatus;

    public ItemTags() {
    }

    public ItemTags(final String id, final Tags tags, final Item item, final String itemTagsStatus) {
        this.id = id;
        this.tags = tags;
        this.item = item;
        this.itemTagsStatus = itemTagsStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_id", nullable = false)
    public Item getItem() {
        return item;
    }

    @Column(name = "item_tags_status", nullable = false, length = 10)
    public String getItemTagsStatus() {
        return itemTagsStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tags_id", nullable = false)
    public Tags getTags() {
        return tags;
    }

    public void setItem(final Item item) {
        this.item = item;
    }

    public void setItemTagsStatus(final String itemTagsStatus) {
        this.itemTagsStatus = itemTagsStatus;
    }

    public void setTags(final Tags tags) {
        this.tags = tags;
    }

}
