package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * ItemAttributes generated by hbm2java
 */
@Entity
@Table(name = "item_attributes", catalog = "meat_app")
public class ItemAttributes extends AbstractDomain implements java.io.Serializable {

    private Attributes attributes;
    private Item item;
    private String attributeName;
    private String attributeValue;
    private String status;
    private CategoryAttributes categoryAttributes;
    private Integer countFlag;
    private String searchableStatus;

    public ItemAttributes() {
    }

    public ItemAttributes(final String id, final Attributes attributes, final String attributeName, final Item item,
            final String attributeValue, final String status, final String searchableStatus, final Integer countFlag,
            final CategoryAttributes categoryAttributes) {
        this.id = id;
        this.attributes = attributes;
        this.item = item;
        this.attributeName = attributeName;
        this.attributeValue = attributeValue;
        this.searchableStatus = searchableStatus;
        this.status = status;
        this.countFlag = countFlag;
        this.categoryAttributes = categoryAttributes;
    }

    @Column(name = "attribute_name", length = 100)
    public String getAttributeName() {
        return attributeName;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "attributes_id", nullable = false)
    public Attributes getAttributes() {
        return attributes;
    }

    @Column(name = "attribute_value", nullable = false, length = 100)
    public String getAttributeValue() {
        return attributeValue;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_attributes_id", nullable = false)
    public CategoryAttributes getCategoryAttributes() {
        return categoryAttributes;
    }

    @Column(name = "count_flag")
    public Integer getCountFlag() {
        return countFlag;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_id", nullable = false)
    public Item getItem() {
        return item;
    }

    @Column(name = "searchable_status")
    public String getSearchableStatus() {
        return searchableStatus;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setAttributeName(final String attributeName) {
        this.attributeName = attributeName;
    }

    public void setAttributes(final Attributes attributes) {
        this.attributes = attributes;
    }

    public void setAttributeValue(final String attributeValue) {
        this.attributeValue = attributeValue;
    }

    public void setCategoryAttributes(final CategoryAttributes categoryAttributes) {
        this.categoryAttributes = categoryAttributes;
    }

    public void setCountFlag(final Integer countFlag) {
        this.countFlag = countFlag;
    }

    public void setItem(final Item item) {
        this.item = item;
    }

    public void setSearchableStatus(final String searchableStatus) {
        this.searchableStatus = searchableStatus;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
