package com.meat.domain;

// Generated Feb 13, 2016 10:49:53 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * OfferConfig generated by hbm2java
 */
@Entity
@Table(name = "offer_config", catalog = "meat_app")
public class OfferConfig extends AbstractDomain implements java.io.Serializable {

    private Tags tags;
    private Seller seller;
    private Item item;
    private SellerItem sellerItem;
    private Offer offer;
    private Category category;
    private SellerBranch sellerBranch;
    private SubCategory subCategory;
    private BankOffer bankOffer;
    private String status;
    private String placedByStatus;
    private String offerAttributeName;
    private String offerAttributeValue;
    /*  private String statusFlag;*/
    private Set<UsersOffer> usersOffers = new HashSet<UsersOffer>(0);

    public OfferConfig() {
    }

    public OfferConfig(final String id, final Offer offer, final String status, final String offerAttributeName,
            final String offerAttributeValue/*, final String statusFlag*/) {
        this.id = id;
        this.offer = offer;
        this.status = status;
        this.offerAttributeName = offerAttributeName;
        this.offerAttributeValue = offerAttributeValue;
        //this.statusFlag = statusFlag;
    }

    public OfferConfig(final String id, final Tags tags, final Seller seller, final Item item, final SellerItem sellerItem,
            final Offer offer, final Category category, final SellerBranch sellerBranch, final SubCategory subCategory,
            final BankOffer bankOffer, final String offerAttributeName, final String offerAttributeValue, final String status,
            final String placedByStatus, final Set<UsersOffer> usersOffers) {
        this.id = id;
        this.tags = tags;
        this.seller = seller;
        this.item = item;
        this.sellerItem = sellerItem;
        this.offer = offer;
        this.category = category;
        this.sellerBranch = sellerBranch;
        this.subCategory = subCategory;
        this.bankOffer = bankOffer;
        this.status = status;
        this.offerAttributeName = offerAttributeName;
        this.offerAttributeValue = offerAttributeValue;
        this.placedByStatus = placedByStatus;
        this.usersOffers = usersOffers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bank_offer_id")
    public BankOffer getBankOffer() {
        return bankOffer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    public Category getCategory() {
        return category;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_id")
    public Item getItem() {
        return item;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "offer_id", nullable = false)
    public Offer getOffer() {
        return offer;
    }

    /**
     * @return the offerAttributeName
     */
    @Column(name = "offer_attribute_name")
    public String getOfferAttributeName() {
        return offerAttributeName;
    }

    /**
     * @return the offerAttributeValue
     */
    @Column(name = "offer_attribute_value")
    public String getOfferAttributeValue() {
        return offerAttributeValue;
    }

    @Column(name = "placed_by_status", length = 100)
    public String getPlacedByStatus() {
        return placedByStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_id")
    public Seller getSeller() {
        return seller;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_branch_id")
    public SellerBranch getSellerBranch() {
        return sellerBranch;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_item_id")
    public SellerItem getSellerItem() {
        return sellerItem;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    /**
     * @return the statusFlag
     */
    /* public String getStatusFlag() {
        return statusFlag;
    }*/

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sub_category_id")
    public SubCategory getSubCategory() {
        return subCategory;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tags_id")
    public Tags getTags() {
        return tags;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "offerConfig")
    public Set<UsersOffer> getUsersOffers() {
        return usersOffers;
    }

    public void setBankOffer(final BankOffer bankOffer) {
        this.bankOffer = bankOffer;
    }

    public void setCategory(final Category category) {
        this.category = category;
    }

    public void setItem(final Item item) {
        this.item = item;
    }

    public void setOffer(final Offer offer) {
        this.offer = offer;
    }

    /**
     * @param offerAttributeName
     *            the offerAttributeName to set
     */
    public void setOfferAttributeName(final String offerAttributeName) {
        this.offerAttributeName = offerAttributeName;
    }

    /**
     * @param offerAttributeValue
     *            the offerAttributeValue to set
     */
    public void setOfferAttributeValue(final String offerAttributeValue) {
        this.offerAttributeValue = offerAttributeValue;
    }

    public void setPlacedByStatus(final String placedByStatus) {
        this.placedByStatus = placedByStatus;
    }

    public void setSeller(final Seller seller) {
        this.seller = seller;
    }

    public void setSellerBranch(final SellerBranch sellerBranch) {
        this.sellerBranch = sellerBranch;
    }

    public void setSellerItem(final SellerItem sellerItem) {
        this.sellerItem = sellerItem;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    /**
     * @param statusFlag
     *            the statusFlag to set
     */
    /*  public void setStatusFlag(final String statusFlag) {
        this.statusFlag = statusFlag;
    }*/

    public void setSubCategory(final SubCategory subCategory) {
        this.subCategory = subCategory;
    }

    public void setTags(final Tags tags) {
        this.tags = tags;
    }

    public void setUsersOffers(final Set<UsersOffer> usersOffers) {
        this.usersOffers = usersOffers;
    }

}
