package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "meat_app")
public class Orders extends AbstractDomain implements java.io.Serializable {

    private Users users;
    private String name;
    private String status;
    private Integer rating;
    private String comments;
    private String transactionId;
    private String itemInfo;
    private BigDecimal amount;
    private BigDecimal discount;
    private BigDecimal shippingCharges;
    private String orderCreatedTime;
    private Date orderModifiedDate;
    private String orderModifiedTime;
    private String orderCode;
    private long orderCount;
    private Integer countFlag;
    private Date orderCreatedDate;
    private String orderDetails;
    private String paymentMode;
    private Set<OrderDeliveryOptions> orderDeliveryOptionses = new HashSet<OrderDeliveryOptions>(0);
    private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
    private Set<Shipment> shipments = new HashSet<Shipment>(0);
    private Set<OrderStatusCodes> orderStatusCodeses = new HashSet<OrderStatusCodes>(0);
    private Set<SubOrder> subOrders = new HashSet<SubOrder>(0);

    public Orders() {
    }

    public Orders(final String id, final Users users, final String status, final BigDecimal amount, final String orderCreatedTime,
            final String orderCode, final long orderCount) {
        this.id = id;
        this.users = users;
        this.status = status;
        this.amount = amount;
        this.orderCreatedTime = orderCreatedTime;
        this.orderCode = orderCode;
        this.orderCount = orderCount;
    }

    public Orders(final String id, final Users users, final String name, final String status, final Integer rating, final String comments,
            final String transactionId, final String itemInfo, final BigDecimal amount, final BigDecimal discount,
            final BigDecimal shippingCharges, final String orderCreatedTime, final Date orderModifiedDate, final String orderModifiedTime,
            final String orderCode, final Integer countFlag, final long orderCount, final Date orderCreatedDate, final String orderDetails,
            final Set<OrderDeliveryOptions> orderDeliveryOptionses, final Set<SubOrder> subOrders, final Set<OrderItem> orderItems,
            final Set<Shipment> shipments, final Set<OrderStatusCodes> orderStatusCodeses) {
        this.id = id;
        this.users = users;
        this.name = name;
        this.status = status;
        this.rating = rating;
        this.comments = comments;
        this.transactionId = transactionId;
        this.itemInfo = itemInfo;
        this.amount = amount;
        this.discount = discount;
        this.shippingCharges = shippingCharges;
        this.orderCreatedTime = orderCreatedTime;
        this.orderModifiedDate = orderModifiedDate;
        this.orderModifiedTime = orderModifiedTime;
        this.orderCode = orderCode;
        this.countFlag = countFlag;
        this.orderCount = orderCount;
        this.orderCreatedDate = orderCreatedDate;
        this.orderDetails = orderDetails;
        this.orderDeliveryOptionses = orderDeliveryOptionses;
        this.orderItems = orderItems;
        this.shipments = shipments;
        this.subOrders = subOrders;
        this.orderStatusCodeses = orderStatusCodeses;
    }

    @Column(name = "amount", nullable = false, precision = 7)
    public BigDecimal getAmount() {
        return amount;
    }

    @Column(name = "comments")
    public String getComments() {
        return comments;
    }

    @Column(name = "count_flag")
    public Integer getCountFlag() {
        return countFlag;
    }

    @Column(name = "discount", precision = 7)
    public BigDecimal getDiscount() {
        return discount;
    }

    @Column(name = "item_info", length = 100)
    public String getItemInfo() {
        return itemInfo;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return name;
    }

    @Column(name = "order_code", nullable = false, length = 45)
    public String getOrderCode() {
        return orderCode;
    }

    @Column(name = "order_count", nullable = false)
    public long getOrderCount() {
        return orderCount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "order_created_date", length = 19)
    public Date getOrderCreatedDate() {
        return orderCreatedDate;
    }

    @Column(name = "order_created_time", nullable = false, length = 45)
    public String getOrderCreatedTime() {
        return orderCreatedTime;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
    public Set<OrderDeliveryOptions> getOrderDeliveryOptionses() {
        return orderDeliveryOptionses;
    }

    @Column(name = "order_details", length = 500)
    public String getOrderDetails() {
        return orderDetails;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
    public Set<OrderItem> getOrderItems() {
        return orderItems;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "order_modified_date", length = 10)
    public Date getOrderModifiedDate() {
        return orderModifiedDate;
    }

    @Column(name = "order_modified_time", length = 45)
    public String getOrderModifiedTime() {
        return orderModifiedTime;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
    public Set<OrderStatusCodes> getOrderStatusCodeses() {
        return orderStatusCodeses;
    }

    /**
     * @return the paymentMode
     */
    @Column(name = "payment_mode")
    public String getPaymentMode() {
        return paymentMode;
    }

    @Column(name = "rating")
    public Integer getRating() {
        return rating;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
    public Set<Shipment> getShipments() {
        return shipments;
    }

    @Column(name = "shipping_charges", precision = 7)
    public BigDecimal getShippingCharges() {
        return shippingCharges;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    /**
     * @return the subOrders
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
    public Set<SubOrder> getSubOrders() {
        return subOrders;
    }

    @Column(name = "transaction_id", length = 100)
    public String getTransactionId() {
        return transactionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id", nullable = false)
    public Users getUsers() {
        return users;
    }

    public void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    public void setComments(final String comments) {
        this.comments = comments;
    }

    public void setCountFlag(final Integer countFlag) {
        this.countFlag = countFlag;
    }

    public void setDiscount(final BigDecimal discount) {
        this.discount = discount;
    }

    public void setItemInfo(final String itemInfo) {
        this.itemInfo = itemInfo;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public void setOrderCode(final String orderCode) {
        this.orderCode = orderCode;
    }

    public void setOrderCount(final long orderCount) {
        this.orderCount = orderCount;
    }

    public void setOrderCreatedDate(final Date orderCreatedDate) {
        this.orderCreatedDate = orderCreatedDate;
    }

    public void setOrderCreatedTime(final String orderCreatedTime) {
        this.orderCreatedTime = orderCreatedTime;
    }

    public void setOrderDeliveryOptionses(final Set<OrderDeliveryOptions> orderDeliveryOptionses) {
        this.orderDeliveryOptionses = orderDeliveryOptionses;
    }

    public void setOrderDetails(final String orderDetails) {
        this.orderDetails = orderDetails;
    }

    public void setOrderItems(final Set<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }

    public void setOrderModifiedDate(final Date orderModifiedDate) {
        this.orderModifiedDate = orderModifiedDate;
    }

    public void setOrderModifiedTime(final String orderModifiedTime) {
        this.orderModifiedTime = orderModifiedTime;
    }

    public void setOrderStatusCodeses(final Set<OrderStatusCodes> orderStatusCodeses) {
        this.orderStatusCodeses = orderStatusCodeses;
    }

    /**
     * @param paymentMode
     *            the paymentMode to set
     */
    public void setPaymentMode(final String paymentMode) {
        this.paymentMode = paymentMode;
    }

    public void setRating(final Integer rating) {
        this.rating = rating;
    }

    public void setShipments(final Set<Shipment> shipments) {
        this.shipments = shipments;
    }

    public void setShippingCharges(final BigDecimal shippingCharges) {
        this.shippingCharges = shippingCharges;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    /**
     * @param subOrders
     *            the subOrders to set
     */
    public void setSubOrders(final Set<SubOrder> subOrders) {
        this.subOrders = subOrders;
    }

    public void setTransactionId(final String transactionId) {
        this.transactionId = transactionId;
    }

    public void setUsers(final Users users) {
        this.users = users;
    }

}
