package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.*;

/**
 * OrderStatusCodes generated by hbm2java
 */
@Entity
@Table(name = "order_status_codes", catalog = "meat_app")
public class OrderStatusCodes extends AbstractDomain implements java.io.Serializable {

    private Orders orders;
    private String orderStatusCode;
    private String orderStatusDescription;
    private Date orderStatusDate;

    public OrderStatusCodes() {
    }

    public OrderStatusCodes(final String id, final Orders orders, final String orderStatusCode, final Date orderStatusDate) {
        this.id = id;
        this.orders = orders;
        this.orderStatusCode = orderStatusCode;
        this.orderStatusDate = orderStatusDate;
    }

    public OrderStatusCodes(final String id, final Orders orders, final String orderStatusCode, final String orderStatusDescription,
            final Date orderStatusDate) {
        this.id = id;
        this.orders = orders;
        this.orderStatusCode = orderStatusCode;
        this.orderStatusDescription = orderStatusDescription;
        this.orderStatusDate = orderStatusDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    public Orders getOrders() {
        return orders;
    }

    @Column(name = "order_status_code", nullable = false, length = 45)
    public String getOrderStatusCode() {
        return orderStatusCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "order_status_date", nullable = false, length = 19)
    public Date getOrderStatusDate() {
        return orderStatusDate;
    }

    @Column(name = "order_status_description", length = 100)
    public String getOrderStatusDescription() {
        return orderStatusDescription;
    }

    public void setOrders(final Orders orders) {
        this.orders = orders;
    }

    public void setOrderStatusCode(final String orderStatusCode) {
        this.orderStatusCode = orderStatusCode;
    }

    public void setOrderStatusDate(final Date orderStatusDate) {
        this.orderStatusDate = orderStatusDate;
    }

    public void setOrderStatusDescription(final String orderStatusDescription) {
        this.orderStatusDescription = orderStatusDescription;
    }

}
