package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.*;

/**
 * OrderDeliveryOptions generated by hbm2java
 */
@Entity
@Table(name = "order_delivery_options", catalog = "meat_app")
public class OrderDeliveryOptions extends AbstractDomain implements java.io.Serializable {

    private Orders orders;
    private BigDecimal shippingCost;
    private Address address;

    public OrderDeliveryOptions() {
    }

    public OrderDeliveryOptions(final String id, final Address address, final Orders orders, final BigDecimal shippingCost,
            final String shippingAddressId) {
        this.id = id;
        this.address = address;
        this.orders = orders;
        this.shippingCost = shippingCost;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "shipping_address_id", nullable = false)
    public Address getAddress() {
        return address;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "orders_id", nullable = false)
    public Orders getOrders() {
        return orders;
    }

    @Column(name = "shipping_cost", nullable = false, precision = 7)
    public BigDecimal getShippingCost() {
        return shippingCost;
    }

    public void setAddress(final Address address) {
        this.address = address;
    }

    public void setOrders(final Orders orders) {
        this.orders = orders;
    }

    public void setShippingCost(final BigDecimal shippingCost) {
        this.shippingCost = shippingCost;
    }

}
