package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "meat_app")
public class Roles extends AbstractDomain implements java.io.Serializable {

    private Users users;
    private String roleName;
    private String enabled;
    private String description;

    public Roles() {
    }

    public Roles(final String id, final Users users, final String roleName, final String enabled) {
        this.id = id;
        this.users = users;
        this.roleName = roleName;
        this.enabled = enabled;
    }

    public Roles(final String id, final Users users, final String roleName, final String enabled, final String description) {
        this.id = id;
        this.users = users;
        this.roleName = roleName;
        this.enabled = enabled;
        this.description = description;
    }

    @Column(name = "description", length = 100)
    public String getDescription() {
        return description;
    }

    @Column(name = "enabled", nullable = false, length = 45)
    public String getEnabled() {
        return enabled;
    }

    @Column(name = "role_name", nullable = false, length = 45)
    public String getRoleName() {
        return roleName;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id", nullable = false)
    public Users getUsers() {
        return users;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setEnabled(final String enabled) {
        this.enabled = enabled;
    }

    public void setRoleName(final String roleName) {
        this.roleName = roleName;
    }

    public void setUsers(final Users users) {
        this.users = users;
    }

}
