package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * SellerItemImages generated by hbm2java
 */
@Entity
@Table(name = "seller_item_images", catalog = "meat_app")
public class SellerItemImages extends AbstractDomain implements java.io.Serializable {

    private SellerItem sellerItem;
    private String imageName;
    private String imageLocation;
    private String imageType;

    public SellerItemImages() {
    }

    public SellerItemImages(final String id, final SellerItem sellerItem, final String imageName, final String imageLocation,
            final String imageType) {
        this.id = id;
        this.sellerItem = sellerItem;
        this.imageName = imageName;
        this.imageLocation = imageLocation;
        this.imageType = imageType;
    }

    @Column(name = "image_location", nullable = false, length = 100)
    public String getImageLocation() {
        return imageLocation;
    }

    @Column(name = "image_name", nullable = false, length = 100)
    public String getImageName() {
        return imageName;
    }

    @Column(name = "image_type", nullable = false, length = 45)
    public String getImageType() {
        return imageType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_item_id", nullable = false)
    public SellerItem getSellerItem() {
        return sellerItem;
    }

    public void setImageLocation(final String imageLocation) {
        this.imageLocation = imageLocation;
    }

    public void setImageName(final String imageName) {
        this.imageName = imageName;
    }

    public void setImageType(final String imageType) {
        this.imageType = imageType;
    }

    public void setSellerItem(final SellerItem sellerItem) {
        this.sellerItem = sellerItem;
    }

}
