package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * SellerBranchAddress generated by hbm2java
 */
@Entity
@Table(name = "seller_branch_address", catalog = "meat_app")
public class SellerBranchAddress extends AbstractDomain implements java.io.Serializable {

    private Address address;
    private SellerBranch sellerBranch;
    private String status;

    public SellerBranchAddress() {
    }

    public SellerBranchAddress(final Address address, final SellerBranch sellerBranch) {
        this.address = address;
        this.sellerBranch = sellerBranch;
    }

    public SellerBranchAddress(final Address address, final SellerBranch sellerBranch, final String status) {
        this.address = address;
        this.sellerBranch = sellerBranch;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "address_id", nullable = false)
    public Address getAddress() {
        return address;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_branch_id", nullable = false)
    public SellerBranch getSellerBranch() {
        return sellerBranch;
    }

    /*  @Column(name = "status", length = 45)
      public String getStatus() {
          return status;
      }*/

    public void setAddress(final Address address) {
        this.address = address;
    }

    public void setSellerBranch(final SellerBranch sellerBranch) {
        this.sellerBranch = sellerBranch;
    }

    /**
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /* public void setStatus(final String status) {
         this.status = status;
     }
    */
}
