package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * SellerItemCriteria generated by hbm2java
 */
@Entity
@Table(name = "seller_item_criteria", catalog = "meat_app")
public class SellerItemCriteria extends AbstractDomain implements java.io.Serializable {

    private SellerItem sellerItem;
    private Criteria criteria;
    private String sellerItemCriteriaStatus;

    public SellerItemCriteria() {
    }

    public SellerItemCriteria(final String id, final SellerItem sellerItem, final Criteria criteria,
            final String sellerItemCriteriaStatus) {
        this.id = id;
        this.sellerItem = sellerItem;
        this.criteria = criteria;
        this.sellerItemCriteriaStatus = sellerItemCriteriaStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "criteria_id", nullable = false)
    public Criteria getCriteria() {
        return criteria;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_item_id", nullable = false)
    public SellerItem getSellerItem() {
        return sellerItem;
    }

    @Column(name = "seller_item_criteria_status", nullable = false, length = 10)
    public String getSellerItemCriteriaStatus() {
        return sellerItemCriteriaStatus;
    }

    public void setCriteria(final Criteria criteria) {
        this.criteria = criteria;
    }

    public void setSellerItem(final SellerItem sellerItem) {
        this.sellerItem = sellerItem;
    }

    public void setSellerItemCriteriaStatus(final String sellerItemCriteriaStatus) {
        this.sellerItemCriteriaStatus = sellerItemCriteriaStatus;
    }

}
