package com.meat.domain;

// Generated Feb 8, 2016 5:13:42 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * SellerInvoice generated by hbm2java
 */
@Entity
@Table(name = "seller_invoice", catalog = "meat_app")
public class SellerInvoice extends AbstractDomain implements java.io.Serializable {

    private SellerBranch sellerBranch;
    private BigDecimal totalAmount;
    private BigDecimal tax;
    private BigDecimal discount;
    private BigDecimal grandTotalAmount;
    private String period;
    private BigDecimal meatInvoiceAmount;
    private String meatInvoiceTax;
    private BigDecimal meatInvoiceDiscount;
    private String paidStatus;
    private Date createdDate;
    private String referenceDocumentNo;
    private String transferMode;
    private String receiptNo;
    private BigDecimal amountToBePaid;
    private BigDecimal previousInvoiceAmount;
    private BigDecimal dueAmount;
    private BigDecimal cancelledSubOrdersAmount;
    private BigDecimal codBilledAmount;
    private BigDecimal paymentGatewayBilledAmount;
    private String description;
    private Set<Receipt> receipts = new HashSet<Receipt>(0);
    private Set<InvoiceTransaction> invoiceTransactions = new HashSet<InvoiceTransaction>(0);
    private Set<MeatInvoice> meatInvoices = new HashSet<MeatInvoice>(0);
    private Set<SubOrder> subOrders = new HashSet<SubOrder>(0);

    public SellerInvoice() {
    }

    public SellerInvoice(final String id, final SellerBranch sellerBranch, final BigDecimal totalAmount, final BigDecimal tax,
            final BigDecimal discount, final BigDecimal grandTotalAmount, final String period, final BigDecimal meatInvoiceAmount,
            final String meatInvoiceTax, final BigDecimal meatInvoiceDiscount, final String paidStatus, final Date createdDate,
            final String referenceDocumentNo, final String transferMode, final String receiptNo, final BigDecimal amountToBePaid,
            final BigDecimal previousInvoiceAmount, final BigDecimal dueAmount, final Set<Receipt> receipts,
            final Set<InvoiceTransaction> invoiceTransactions, final Set<MeatInvoice> meatInvoices, final Set<SubOrder> subOrders,
            final BigDecimal cancelledSubOrdersAmount, final BigDecimal paymentGatewayBilledAmount, final BigDecimal codBilledAmount,
            final String description) {
        this.id = id;
        this.sellerBranch = sellerBranch;
        this.totalAmount = totalAmount;
        this.tax = tax;
        this.discount = discount;
        this.grandTotalAmount = grandTotalAmount;
        this.period = period;
        this.meatInvoiceAmount = meatInvoiceAmount;
        this.meatInvoiceTax = meatInvoiceTax;
        this.meatInvoiceDiscount = meatInvoiceDiscount;
        this.paidStatus = paidStatus;
        this.createdDate = createdDate;
        this.referenceDocumentNo = referenceDocumentNo;
        this.transferMode = transferMode;
        this.receiptNo = receiptNo;
        this.amountToBePaid = amountToBePaid;
        this.previousInvoiceAmount = previousInvoiceAmount;
        this.dueAmount = dueAmount;
        this.receipts = receipts;
        this.invoiceTransactions = invoiceTransactions;
        this.meatInvoices = meatInvoices;
        this.subOrders = subOrders;
        this.cancelledSubOrdersAmount = cancelledSubOrdersAmount;
        this.codBilledAmount = codBilledAmount;
        this.paymentGatewayBilledAmount = paymentGatewayBilledAmount;
        this.description = description;
    }

    public SellerInvoice(final String id, final SellerBranch sellerBranch, final BigDecimal totalAmount, final BigDecimal tax,
            final BigDecimal discount, final BigDecimal grandTotalAmount, final String period, final String paidStatus) {
        this.id = id;
        this.sellerBranch = sellerBranch;
        this.totalAmount = totalAmount;
        this.tax = tax;
        this.discount = discount;
        this.grandTotalAmount = grandTotalAmount;
        this.period = period;
        this.paidStatus = paidStatus;
    }

    @Column(name = "amount_to_be_paid", precision = 20, scale = 5)
    public BigDecimal getAmountToBePaid() {
        return amountToBePaid;
    }

    /**
     * @return the cancelledSubOrdersAmount
     */
    @Column(name = "cancelled_sub_orders_amount", precision = 20, scale = 5)
    public BigDecimal getCancelledSubOrdersAmount() {
        return cancelledSubOrdersAmount;
    }

    /**
     * @return the codBilledAmount
     */
    @Column(name = "cod_billed_amount")
    public BigDecimal getCodBilledAmount() {
        return codBilledAmount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * @return the description
     */
    @Column(name = "description")
    public String getDescription() {
        return description;
    }

    @Column(name = "discount", nullable = false, precision = 3)
    public BigDecimal getDiscount() {
        return discount;
    }

    @Column(name = "due_amount", precision = 20, scale = 5)
    public BigDecimal getDueAmount() {
        return dueAmount;
    }

    @Column(name = "grand_total_amount", nullable = false, precision = 7)
    public BigDecimal getGrandTotalAmount() {
        return grandTotalAmount;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sellerInvoice")
    public Set<InvoiceTransaction> getInvoiceTransactions() {
        return invoiceTransactions;
    }

    @Column(name = "meat_invoice_amount", precision = 7)
    public BigDecimal getMeatInvoiceAmount() {
        return meatInvoiceAmount;
    }

    @Column(name = "meat_invoice_discount", precision = 3)
    public BigDecimal getMeatInvoiceDiscount() {
        return meatInvoiceDiscount;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sellerInvoice")
    public Set<MeatInvoice> getMeatInvoices() {
        return meatInvoices;
    }

    @Column(name = "meat_invoice_tax", length = 45)
    public String getMeatInvoiceTax() {
        return meatInvoiceTax;
    }

    @Column(name = "paid_status", nullable = false, length = 45)
    public String getPaidStatus() {
        return paidStatus;
    }

    /**
     * @return the paymentGatewayBilledAmount
     */
    @Column(name = "payment_gateway_billed_amount")
    public BigDecimal getPaymentGatewayBilledAmount() {
        return paymentGatewayBilledAmount;
    }

    @Column(name = "period", nullable = false, length = 100)
    public String getPeriod() {
        return period;
    }

    @Column(name = "previous_invoice_amount", precision = 20, scale = 5)
    public BigDecimal getPreviousInvoiceAmount() {
        return previousInvoiceAmount;
    }

    @Column(name = "receipt_no", length = 45)
    public String getReceiptNo() {
        return receiptNo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sellerInvoice")
    public Set<Receipt> getReceipts() {
        return receipts;
    }

    @Column(name = "reference_document_no", length = 45)
    public String getReferenceDocumentNo() {
        return referenceDocumentNo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_branch_id", nullable = false)
    public SellerBranch getSellerBranch() {
        return sellerBranch;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sellerInvoice")
    public Set<SubOrder> getSubOrders() {
        return subOrders;
    }

    @Column(name = "tax", nullable = false, precision = 7)
    public BigDecimal getTax() {
        return tax;
    }

    @Column(name = "total_amount", nullable = false, precision = 7)
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    @Column(name = "transfer_mode", length = 45)
    public String getTransferMode() {
        return transferMode;
    }

    public void setAmountToBePaid(final BigDecimal amountToBePaid) {
        this.amountToBePaid = amountToBePaid;
    }

    /**
     * @param cancelledSubOrdersAmount
     *            the cancelledSubOrdersAmount to set
     */
    public void setCancelledSubOrdersAmount(final BigDecimal cancelledSubOrdersAmount) {
        this.cancelledSubOrdersAmount = cancelledSubOrdersAmount;
    }

    /**
     * @param codBilledAmount
     *            the codBilledAmount to set
     */
    public void setCodBilledAmount(final BigDecimal codBilledAmount) {
        this.codBilledAmount = codBilledAmount;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * @param description
     *            the description to set
     */
    public void setDescription(final String description) {
        this.description = description;
    }

    public void setDiscount(final BigDecimal discount) {
        this.discount = discount;
    }

    public void setDueAmount(final BigDecimal dueAmount) {
        this.dueAmount = dueAmount;
    }

    public void setGrandTotalAmount(final BigDecimal grandTotalAmount) {
        this.grandTotalAmount = grandTotalAmount;
    }

    public void setInvoiceTransactions(final Set<InvoiceTransaction> invoiceTransactions) {
        this.invoiceTransactions = invoiceTransactions;
    }

    public void setMeatInvoiceAmount(final BigDecimal meatInvoiceAmount) {
        this.meatInvoiceAmount = meatInvoiceAmount;
    }

    public void setMeatInvoiceDiscount(final BigDecimal meatInvoiceDiscount) {
        this.meatInvoiceDiscount = meatInvoiceDiscount;
    }

    public void setMeatInvoices(final Set<MeatInvoice> meatInvoices) {
        this.meatInvoices = meatInvoices;
    }

    public void setMeatInvoiceTax(final String meatInvoiceTax) {
        this.meatInvoiceTax = meatInvoiceTax;
    }

    public void setPaidStatus(final String paidStatus) {
        this.paidStatus = paidStatus;
    }

    /**
     * @param paymentGatewayBilledAmount
     *            the paymentGatewayBilledAmount to set
     */
    public void setPaymentGatewayBilledAmount(final BigDecimal paymentGatewayBilledAmount) {
        this.paymentGatewayBilledAmount = paymentGatewayBilledAmount;
    }

    public void setPeriod(final String period) {
        this.period = period;
    }

    public void setPreviousInvoiceAmount(final BigDecimal previousInvoiceAmount) {
        this.previousInvoiceAmount = previousInvoiceAmount;
    }

    public void setReceiptNo(final String receiptNo) {
        this.receiptNo = receiptNo;
    }

    public void setReceipts(final Set<Receipt> receipts) {
        this.receipts = receipts;
    }

    public void setReferenceDocumentNo(final String referenceDocumentNo) {
        this.referenceDocumentNo = referenceDocumentNo;
    }

    public void setSellerBranch(final SellerBranch sellerBranch) {
        this.sellerBranch = sellerBranch;
    }

    public void setSubOrders(final Set<SubOrder> subOrders) {
        this.subOrders = subOrders;
    }

    public void setTax(final BigDecimal tax) {
        this.tax = tax;
    }

    public void setTotalAmount(final BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public void setTransferMode(final String transferMode) {
        this.transferMode = transferMode;
    }

}
