package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Seller generated by hbm2java
 */
@Entity
@Table(name = "seller", catalog = "meat_app")
public class Seller extends AbstractDomain implements java.io.Serializable {

    private Seo seo;
    private String sellerName;
    private String description;
    private Date createdDate;
    private String status;
    private String sellerCode;
    private long sellerCount;
    private String sellerType;
    private Set<SellerBranch> sellerBranches = new HashSet<SellerBranch>(0);
    private Set<SellerImages> sellerImageses = new HashSet<SellerImages>(0);
    private Set<OfferConfig> offerConfigs = new HashSet<OfferConfig>(0);
    private Set<OfferExcludeConfig> offerExcludeConfigs = new HashSet<OfferExcludeConfig>(0);

    public Seller() {
    }

    public Seller(final String id, final Seo seo, final String sellerName, final String description, final Date createdDate,
            final String status, final String sellerCode, final long sellerCount, final Set<SellerBranch> sellerBranches,
            final Set<SellerImages> sellerImageses, final Set<OfferExcludeConfig> offerExcludeConfigs,
            final Set<OfferConfig> offerConfigs) {
        this.id = id;
        this.seo = seo;
        this.sellerName = sellerName;
        this.description = description;
        this.createdDate = createdDate;
        this.status = status;
        this.sellerCode = sellerCode;
        this.sellerCount = sellerCount;
        this.sellerBranches = sellerBranches;
        this.offerConfigs = offerConfigs;
        this.offerExcludeConfigs = offerExcludeConfigs;
        this.sellerImageses = sellerImageses;
    }

    public Seller(final String id, final String sellerName, final Date createdDate, final String status, final String sellerCode,
            final long sellerCount) {
        this.id = id;
        this.sellerName = sellerName;
        this.createdDate = createdDate;
        this.status = status;
        this.sellerCode = sellerCode;
        this.sellerCount = sellerCount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", nullable = false, length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "description", length = 1500)
    public String getDescription() {
        return description;
    }

    /**
     * @return the offerConfigs
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seller")
    public Set<OfferConfig> getOfferConfigs() {
        return offerConfigs;
    }

    /**
     * @return the offerExcludeConfigs
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seller")
    public Set<OfferExcludeConfig> getOfferExcludeConfigs() {
        return offerExcludeConfigs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seller")
    public Set<SellerBranch> getSellerBranches() {
        return sellerBranches;
    }

    @Column(name = "seller_code", nullable = false, length = 45)
    public String getSellerCode() {
        return sellerCode;
    }

    @Column(name = "seller_count", nullable = false)
    public long getSellerCount() {
        return sellerCount;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seller")
    public Set<SellerImages> getSellerImageses() {
        return sellerImageses;
    }

    @Column(name = "seller_name", nullable = false, length = 45)
    public String getSellerName() {
        return sellerName;
    }

    @Column(name = "seller_type", nullable = false, length = 45)
    public String getSellerType() {
        return sellerType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seo_id")
    public Seo getSeo() {
        return seo;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    /**
     * @param offerConfigs
     *            the offerConfigs to set
     */
    public void setOfferConfigs(final Set<OfferConfig> offerConfigs) {
        this.offerConfigs = offerConfigs;
    }

    /**
     * @param offerExcludeConfigs
     *            the offerExcludeConfigs to set
     */
    public void setOfferExcludeConfigs(final Set<OfferExcludeConfig> offerExcludeConfigs) {
        this.offerExcludeConfigs = offerExcludeConfigs;
    }

    public void setSellerBranches(final Set<SellerBranch> sellerBranches) {
        this.sellerBranches = sellerBranches;
    }

    public void setSellerCode(final String sellerCode) {
        this.sellerCode = sellerCode;
    }

    public void setSellerCount(final long sellerCount) {
        this.sellerCount = sellerCount;
    }

    public void setSellerImageses(final Set<SellerImages> sellerImageses) {
        this.sellerImageses = sellerImageses;
    }

    public void setSellerName(final String sellerName) {
        this.sellerName = sellerName;
    }

    public void setSellerType(final String sellerType) {
        this.sellerType = sellerType;
    }

    public void setSeo(final Seo seo) {
        this.seo = seo;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
