package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.*;

/**
 * SellerItemTax generated by hbm2java
 */
@Entity
@Table(name = "seller_item_tax", catalog = "meat_app")
public class SellerItemTax extends AbstractDomain implements java.io.Serializable {

    private SellerItem sellerItem;
    private SellerBranchTax sellerBranchTax;
    private String sellerItemTaxStatus;
    private float sellerItemTaxValue;
    private Date createdDate;

    public SellerItemTax() {
    }

    public SellerItemTax(final String id, final SellerItem sellerItem, final SellerBranchTax sellerBranchTax,
            final String sellerItemTaxStatus, final float sellerItemTaxValue, final Date createdDate) {
        this.id = id;
        this.sellerItem = sellerItem;
        this.sellerBranchTax = sellerBranchTax;
        this.sellerItemTaxStatus = sellerItemTaxStatus;
        this.sellerItemTaxValue = sellerItemTaxValue;

        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created _date", nullable = false, length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_branch_tax_id", nullable = false)
    public SellerBranchTax getSellerBranchTax() {
        return sellerBranchTax;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_item_id", nullable = false)
    public SellerItem getSellerItem() {
        return sellerItem;
    }

    @Column(name = "seller_item_tax_status", nullable = false, length = 100)
    public String getSellerItemTaxStatus() {
        return sellerItemTaxStatus;
    }

    @Column(name = "seller_item_tax_value", nullable = false, precision = 7)
    public float getSellerItemTaxValue() {
        return sellerItemTaxValue;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setSellerBranchTax(final SellerBranchTax sellerBranchTax) {
        this.sellerBranchTax = sellerBranchTax;
    }

    public void setSellerItem(final SellerItem sellerItem) {
        this.sellerItem = sellerItem;
    }

    public void setSellerItemTaxStatus(final String sellerItemTaxStatus) {
        this.sellerItemTaxStatus = sellerItemTaxStatus;
    }

    public void setSellerItemTaxValue(final float sellerItemTaxValue) {
        this.sellerItemTaxValue = sellerItemTaxValue;
    }

}
