package com.meat.domain;

// Generated Feb 13, 2016 10:49:53 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * SellerBankAccount generated by hbm2java
 */
@Entity
@Table(name = "seller_bank_account", catalog = "meat_app")
public class SellerBankAccount extends AbstractDomain implements java.io.Serializable {

    private SellerBranch sellerBranch;
    private String accountNo;
    private String ifscCode;
    private String branchDetails;
    private String name;
    private String accountType;
    private String panNumber;

    public SellerBankAccount() {
    }

    public SellerBankAccount(final String id, final SellerBranch sellerBranch, final String accountNo, final String ifscCode,
            final String branchDetails, final String name, final String accountType, final String panNumber) {
        this.id = id;
        this.sellerBranch = sellerBranch;
        this.accountNo = accountNo;
        this.ifscCode = ifscCode;
        this.branchDetails = branchDetails;
        this.name = name;
        this.panNumber = panNumber;
    }

    @Column(name = "account_no", nullable = false, length = 45)
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * @return the accountType
     */
    @Column(name = "account_type")
    public String getAccountType() {
        return accountType;
    }

    @Column(name = "branch_details", nullable = false, length = 45)
    public String getBranchDetails() {
        return branchDetails;
    }

    @Column(name = "ifsc_code", nullable = false, length = 45)
    public String getIfscCode() {
        return ifscCode;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return name;
    }

    /**
     * @return the panNumber
     */
    @Column(name = "pan_number")
    public String getPanNumber() {
        return panNumber;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_branch_id", nullable = false)
    public SellerBranch getSellerBranch() {
        return sellerBranch;
    }

    public void setAccountNo(final String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * @param accountType
     *            the accountType to set
     */
    public void setAccountType(final String accountType) {
        this.accountType = accountType;
    }

    public void setBranchDetails(final String branchDetails) {
        this.branchDetails = branchDetails;
    }

    public void setIfscCode(final String ifscCode) {
        this.ifscCode = ifscCode;
    }

    public void setName(final String name) {
        this.name = name;
    }

    /**
     * @param panNumber
     *            the panNumber to set
     */
    public void setPanNumber(final String panNumber) {
        this.panNumber = panNumber;
    }

    public void setSellerBranch(final SellerBranch sellerBranch) {
        this.sellerBranch = sellerBranch;
    }

}
