package com.meat.domain;

// Generated Jan 11, 2016 12:46:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.*;

/**
 * SellerTimingsConfig generated by hbm2java
 */
@Entity
@Table(name = "seller_timings_config", catalog = "meat_app")
public class SellerTimingsConfig extends AbstractDomain implements java.io.Serializable {

    private SellerBranchTimings sellerBranchTimings;
    private String status;
    private Date createdDate;
    private Date serviceOffDate;

    public SellerTimingsConfig() {
    }

    public SellerTimingsConfig(final String id, final SellerBranchTimings sellerBranchTimings, final String status,
            final Date serviceOffDate) {
        this.id = id;
        this.sellerBranchTimings = sellerBranchTimings;
        this.status = status;
        this.serviceOffDate = serviceOffDate;
    }

    public SellerTimingsConfig(final String id, final SellerBranchTimings sellerBranchTimings, final String status, final Date createdDate,
            final Date serviceOffDate) {
        this.id = id;
        this.sellerBranchTimings = sellerBranchTimings;
        this.status = status;
        this.createdDate = createdDate;
        this.serviceOffDate = serviceOffDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_branch_timings_id", nullable = false)
    public SellerBranchTimings getSellerBranchTimings() {
        return sellerBranchTimings;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "service_off_date", nullable = false, length = 19)
    public Date getServiceOffDate() {
        return serviceOffDate;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setSellerBranchTimings(final SellerBranchTimings sellerBranchTimings) {
        this.sellerBranchTimings = sellerBranchTimings;
    }

    public void setServiceOffDate(final Date serviceOffDate) {
        this.serviceOffDate = serviceOffDate;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

}
