package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.*;

/**
 * SellerRequests generated by hbm2java
 */
@Entity
@Table(name = "seller_requests", catalog = "meat_app")
public class SellerRequests extends AbstractDomain implements java.io.Serializable {

    private String requestName;
    private String requestType;
    private String requestStatus;
    private String description;
    private Date requestDate;
    private String userCreated;
    private Date dateCreated;
    private String userModified;
    private Date dateModified;
    private String sellerBranchId;

    public SellerRequests() {
    }

    public SellerRequests(final String id, final String requestName, final String requestType, final String requestStatus,
            final String userCreated, final Date dateCreated, final String sellerBranchId) {
        this.id = id;
        this.requestName = requestName;
        this.requestType = requestType;
        this.requestStatus = requestStatus;
        this.userCreated = userCreated;
        this.dateCreated = dateCreated;
        this.sellerBranchId = sellerBranchId;
    }

    public SellerRequests(final String id, final String requestName, final String requestType, final String requestStatus,
            final String description, final Date requestDate, final String userCreated, final Date dateCreated, final String userModified,
            final Date dateModified, final String sellerBranchId) {
        this.id = id;
        this.requestName = requestName;
        this.requestType = requestType;
        this.requestStatus = requestStatus;
        this.description = description;
        this.requestDate = requestDate;
        this.userCreated = userCreated;
        this.dateCreated = dateCreated;
        this.userModified = userModified;
        this.dateModified = dateModified;
        this.sellerBranchId = sellerBranchId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_created", nullable = false, length = 19)
    public Date getDateCreated() {
        return dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date_modified", length = 19)
    public Date getDateModified() {
        return dateModified;
    }

    @Column(name = "description")
    public String getDescription() {
        return description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "request_date", length = 19)
    public Date getRequestDate() {
        return requestDate;
    }

    @Column(name = "request_name", nullable = false, length = 45)
    public String getRequestName() {
        return requestName;
    }

    @Column(name = "request_status", nullable = false, length = 45)
    public String getRequestStatus() {
        return requestStatus;
    }

    @Column(name = "request_type", nullable = false, length = 45)
    public String getRequestType() {
        return requestType;
    }

    @Column(name = "seller_branch_id", nullable = false, length = 100)
    public String getSellerBranchId() {
        return sellerBranchId;
    }

    @Column(name = "user_created", nullable = false, length = 45)
    public String getUserCreated() {
        return userCreated;
    }

    @Column(name = "user_modified", length = 45)
    public String getUserModified() {
        return userModified;
    }

    public void setDateCreated(final Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public void setDateModified(final Date dateModified) {
        this.dateModified = dateModified;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setRequestDate(final Date requestDate) {
        this.requestDate = requestDate;
    }

    public void setRequestName(final String requestName) {
        this.requestName = requestName;
    }

    public void setRequestStatus(final String requestStatus) {
        this.requestStatus = requestStatus;
    }

    public void setRequestType(final String requestType) {
        this.requestType = requestType;
    }

    public void setSellerBranchId(final String sellerBranchId) {
        this.sellerBranchId = sellerBranchId;
    }

    public void setUserCreated(final String userCreated) {
        this.userCreated = userCreated;
    }

    public void setUserModified(final String userModified) {
        this.userModified = userModified;
    }

}
