package com.meat.domain;

// Generated Jan 11, 2016 12:46:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.*;

/**
 * SellerBranchZone generated by hbm2java
 */
@Entity
@Table(name = "seller_branch_zone", catalog = "meat_app")
public class SellerBranchZone extends AbstractDomain implements java.io.Serializable {

    private Zone zone;
    private SellerBranch sellerBranch;
    private String status;
    private Date createdDate;

    public SellerBranchZone() {
    }

    public SellerBranchZone(final String id, final Zone zone, final SellerBranch sellerBranch, final String status) {
        this.id = id;
        this.zone = zone;
        this.sellerBranch = sellerBranch;
        this.status = status;
    }

    public SellerBranchZone(final String id, final Zone zone, final SellerBranch sellerBranch, final String status,
            final Date createdDate) {
        this.id = id;
        this.zone = zone;
        this.sellerBranch = sellerBranch;
        this.status = status;
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_branch_id", nullable = false)
    public SellerBranch getSellerBranch() {
        return sellerBranch;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "zone_id", nullable = false)
    public Zone getZone() {
        return zone;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setSellerBranch(final SellerBranch sellerBranch) {
        this.sellerBranch = sellerBranch;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    public void setZone(final Zone zone) {
        this.zone = zone;
    }

}
