package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Seo generated by hbm2java
 */
@Entity
@Table(name = "seo", catalog = "meat_app")
public class Seo extends AbstractDomain implements java.io.Serializable {

    private String seoTitle;
    private String seoKeywords;
    private String seoMetaDescription;
    private Set<SubCategory> subCategories = new HashSet<SubCategory>(0);
    private Set<Criteria> criterias = new HashSet<Criteria>(0);
    private Set<Tags> tagses = new HashSet<Tags>(0);
    private Set<Category> categories = new HashSet<Category>(0);
    private Set<Attributes> attributeses = new HashSet<Attributes>(0);
    private Set<Item> items = new HashSet<Item>(0);
    private Set<Seller> sellers = new HashSet<Seller>(0);
    private Set<SellerItem> sellerItems = new HashSet<SellerItem>(0);

    public Seo() {
    }

    public Seo(final String id, final String seoTitle, final String seoKeywords, final String seoMetaDescription) {
        this.id = id;
        this.seoTitle = seoTitle;
        this.seoKeywords = seoKeywords;
        this.seoMetaDescription = seoMetaDescription;
    }

    public Seo(final String id, final String seoTitle, final String seoKeywords, final String seoMetaDescription,
            final Set<SubCategory> subCategories, final Set<Criteria> criterias, final Set<Tags> tagses, final Set<Category> categories,
            final Set<Attributes> attributeses, final Set<Item> items, final Set<Seller> sellers, final Set<SellerItem> sellerItems) {
        this.id = id;
        this.seoTitle = seoTitle;
        this.seoKeywords = seoKeywords;
        this.seoMetaDescription = seoMetaDescription;
        this.subCategories = subCategories;
        this.criterias = criterias;
        this.tagses = tagses;
        this.categories = categories;
        this.attributeses = attributeses;
        this.items = items;
        this.sellers = sellers;
        this.sellerItems = sellerItems;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seo")
    public Set<Attributes> getAttributeses() {
        return attributeses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seo")
    public Set<Category> getCategories() {
        return categories;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seo")
    public Set<Criteria> getCriterias() {
        return criterias;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seo")
    public Set<Item> getItems() {
        return items;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seo")
    public Set<SellerItem> getSellerItems() {
        return sellerItems;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seo")
    public Set<Seller> getSellers() {
        return sellers;
    }

    @Column(name = "seo_keywords", nullable = false, length = 500)
    public String getSeoKeywords() {
        return seoKeywords;
    }

    @Column(name = "seo_meta_description", nullable = false, length = 500)
    public String getSeoMetaDescription() {
        return seoMetaDescription;
    }

    @Column(name = "seo_title", nullable = false, length = 500)
    public String getSeoTitle() {
        return seoTitle;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seo")
    public Set<SubCategory> getSubCategories() {
        return subCategories;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "seo")
    public Set<Tags> getTagses() {
        return tagses;
    }

    public void setAttributeses(final Set<Attributes> attributeses) {
        this.attributeses = attributeses;
    }

    public void setCategories(final Set<Category> categories) {
        this.categories = categories;
    }

    public void setCriterias(final Set<Criteria> criterias) {
        this.criterias = criterias;
    }

    public void setItems(final Set<Item> items) {
        this.items = items;
    }

    public void setSellerItems(final Set<SellerItem> sellerItems) {
        this.sellerItems = sellerItems;
    }

    public void setSellers(final Set<Seller> sellers) {
        this.sellers = sellers;
    }

    public void setSeoKeywords(final String seoKeywords) {
        this.seoKeywords = seoKeywords;
    }

    public void setSeoMetaDescription(final String seoMetaDescription) {
        this.seoMetaDescription = seoMetaDescription;
    }

    public void setSeoTitle(final String seoTitle) {
        this.seoTitle = seoTitle;
    }

    public void setSubCategories(final Set<SubCategory> subCategories) {
        this.subCategories = subCategories;
    }

    public void setTagses(final Set<Tags> tagses) {
        this.tagses = tagses;
    }

}
