package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Shipment generated by hbm2java
 */
@Entity
@Table(name = "shipment", catalog = "meat_app")
public class Shipment extends AbstractDomain implements java.io.Serializable {

    private Orders orders;
    private String shipmentTrackingNumber;
    private String shipmentDetails;
    private Date shipmentDate;
    // private String invoiceId;
    private Set<ShipmentItems> shipmentItemses = new HashSet<ShipmentItems>(0);

    public Shipment() {
    }

    public Shipment(final String id, final Orders orders, final String shipmentTrackingNumber, final Date shipmentDate) {
        this.id = id;
        this.orders = orders;
        this.shipmentTrackingNumber = shipmentTrackingNumber;
        this.shipmentDate = shipmentDate;
        //   this.invoiceId = invoiceId;
    }

    public Shipment(final String id, final Orders orders, final String shipmentTrackingNumber, final String shipmentDetails,
            final Date shipmentDate, final Set<ShipmentItems> shipmentItemses) {
        this.id = id;
        this.orders = orders;
        this.shipmentTrackingNumber = shipmentTrackingNumber;
        this.shipmentDetails = shipmentDetails;
        this.shipmentDate = shipmentDate;
        //   this.invoiceId = invoiceId;
        this.shipmentItemses = shipmentItemses;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    public Orders getOrders() {
        return orders;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "shipment_date", nullable = false, length = 19)
    public Date getShipmentDate() {
        return shipmentDate;
    }

    @Column(name = "shipment_details", length = 500)
    public String getShipmentDetails() {
        return shipmentDetails;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "shipment")
    public Set<ShipmentItems> getShipmentItemses() {
        return shipmentItemses;
    }

    @Column(name = "shipment_tracking_number", nullable = false, length = 45)
    public String getShipmentTrackingNumber() {
        return shipmentTrackingNumber;
    }

    public void setOrders(final Orders orders) {
        this.orders = orders;
    }

    public void setShipmentDate(final Date shipmentDate) {
        this.shipmentDate = shipmentDate;
    }

    public void setShipmentDetails(final String shipmentDetails) {
        this.shipmentDetails = shipmentDetails;
    }

    public void setShipmentItemses(final Set<ShipmentItems> shipmentItemses) {
        this.shipmentItemses = shipmentItemses;
    }

    public void setShipmentTrackingNumber(final String shipmentTrackingNumber) {
        this.shipmentTrackingNumber = shipmentTrackingNumber;
    }

}
