package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * SubCategoryAttributes generated by hbm2java
 */
@Entity
@Table(name = "sub_category_attributes", catalog = "meat_app")
public class SubCategoryAttributes extends AbstractDomain implements java.io.Serializable {

    private Attributes attributes;
    private SubCategory subCategory;
    private String attributeValue;
    private String status;

    public SubCategoryAttributes() {
    }

    public SubCategoryAttributes(final String id, final Attributes attributes, final SubCategory subCategory, final String attributeValue,
            final String status) {
        this.id = id;
        this.attributes = attributes;
        this.subCategory = subCategory;
        this.attributeValue = attributeValue;
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "attributes_id", nullable = false)
    public Attributes getAttributes() {
        return attributes;
    }

    @Column(name = "attribute_value", nullable = false, length = 45)
    public String getAttributeValue() {
        return attributeValue;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sub_category_id", nullable = false)
    public SubCategory getSubCategory() {
        return subCategory;
    }

    public void setAttributes(final Attributes attributes) {
        this.attributes = attributes;
    }

    public void setAttributeValue(final String attributeValue) {
        this.attributeValue = attributeValue;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    public void setSubCategory(final SubCategory subCategory) {
        this.subCategory = subCategory;
    }

}
