package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * SubCategoryTags generated by hbm2java
 */
@Entity
@Table(name = "sub_category_tags", catalog = "meat_app")
public class SubCategoryTags extends AbstractDomain implements java.io.Serializable {

    private Tags tags;
    private SubCategory subCategory;
    private String subCategoryTagsStatus;

    public SubCategoryTags() {
    }

    public SubCategoryTags(final String id, final Tags tags, final SubCategory subCategory, final String subCategoryTagsStatus) {
        this.id = id;
        this.tags = tags;
        this.subCategory = subCategory;
        this.subCategoryTagsStatus = subCategoryTagsStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sub_category_id", nullable = false)
    public SubCategory getSubCategory() {
        return subCategory;
    }

    @Column(name = "sub_category_tags_status", nullable = false, length = 45)
    public String getSubCategoryTagsStatus() {
        return subCategoryTagsStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tags_id", nullable = false)
    public Tags getTags() {
        return tags;
    }

    public void setSubCategory(final SubCategory subCategory) {
        this.subCategory = subCategory;
    }

    public void setSubCategoryTagsStatus(final String subCategoryTagsStatus) {
        this.subCategoryTagsStatus = subCategoryTagsStatus;
    }

    public void setTags(final Tags tags) {
        this.tags = tags;
    }

}
