package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * SubCategory generated by hbm2java
 */
@Entity
@Table(name = "sub_category", catalog = "meat_app")
public class SubCategory extends AbstractDomain implements java.io.Serializable {

    private Seo seo;
    private Category category;
    private String subCategoryName;
    private String description;
    private Date createdDate;
    private String sellingTag;
    private String status;
    private String subCategoryCode;
    private long subCategoryCount;
    private Integer countFlag;
    private Set<Item> items = new HashSet<Item>(0);
    private Set<SubCategoryAttributes> subCategoryAttributeses = new HashSet<SubCategoryAttributes>(0);
    private Set<SubCategoryTags> subCategoryTagses = new HashSet<SubCategoryTags>(0);
    private Set<SubCategoryImages> subCategoryImageses = new HashSet<SubCategoryImages>(0);
    private Set<OfferExcludeConfig> offerExcludeConfigs = new HashSet<OfferExcludeConfig>(0);
    private Set<OfferConfig> offerConfigs = new HashSet<OfferConfig>(0);

    public SubCategory() {
    }

    public SubCategory(final String id, final Seo seo, final Category category, final Integer countFlag, final String subCategoryName,
            final Date createdDate, final String status, final String subCategoryCode, final long subCategoryCount) {
        this.id = id;
        this.seo = seo;
        this.category = category;
        this.subCategoryName = subCategoryName;
        this.countFlag = countFlag;
        this.createdDate = createdDate;
        this.status = status;
        this.subCategoryCode = subCategoryCode;
        this.subCategoryCount = subCategoryCount;
    }

    public SubCategory(final String id, final Seo seo, final Category category, final String subCategoryName, final String description,
            final Date createdDate, final String sellingTag, final String status, final Integer countFlag, final String subCategoryCode,
            final long subCategoryCount, final Set<Item> items, final Set<SubCategoryAttributes> subCategoryAttributeses,
            final Set<SubCategoryTags> subCategoryTagses, final Set<OfferExcludeConfig> offerExcludeConfigs,
            final Set<OfferConfig> offerConfigs, final Set<SubCategoryImages> subCategoryImageses) {
        this.id = id;
        this.seo = seo;
        this.category = category;
        this.subCategoryName = subCategoryName;
        this.description = description;
        this.createdDate = createdDate;
        this.sellingTag = sellingTag;
        this.status = status;
        this.subCategoryCode = subCategoryCode;
        this.subCategoryCount = subCategoryCount;
        this.countFlag = countFlag;
        this.items = items;
        this.subCategoryAttributeses = subCategoryAttributeses;
        this.subCategoryTagses = subCategoryTagses;
        this.subCategoryImageses = subCategoryImageses;
        this.offerConfigs = offerConfigs;
        this.offerExcludeConfigs = offerExcludeConfigs;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    public Category getCategory() {
        return category;
    }

    @Column(name = "count_flag")
    public Integer getCountFlag() {
        return countFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", nullable = false, length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "description", length = 2000)
    public String getDescription() {
        return description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subCategory")
    public Set<Item> getItems() {
        return items;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subCategory")
    public Set<OfferConfig> getOfferConfigs() {
        return offerConfigs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subCategory")
    public Set<OfferExcludeConfig> getOfferExcludeConfigs() {
        return offerExcludeConfigs;
    }

    @Column(name = "selling_tag")
    public String getSellingTag() {
        return sellingTag;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seo_id", nullable = false)
    public Seo getSeo() {
        return seo;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subCategory")
    public Set<SubCategoryAttributes> getSubCategoryAttributeses() {
        return subCategoryAttributeses;
    }

    @Column(name = "sub_category_code", nullable = false, length = 100)
    public String getSubCategoryCode() {
        return subCategoryCode;
    }

    @Column(name = "sub_category_count", nullable = false)
    public long getSubCategoryCount() {
        return subCategoryCount;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subCategory")
    public Set<SubCategoryImages> getSubCategoryImageses() {
        return subCategoryImageses;
    }

    @Column(name = "sub_category_name", nullable = false, length = 60)
    public String getSubCategoryName() {
        return subCategoryName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subCategory")
    public Set<SubCategoryTags> getSubCategoryTagses() {
        return subCategoryTagses;
    }

    public void setCategory(final Category category) {
        this.category = category;
    }

    public void setCountFlag(final Integer countFlag) {
        this.countFlag = countFlag;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setItems(final Set<Item> items) {
        this.items = items;
    }

    public void setOfferConfigs(final Set<OfferConfig> offerConfigs) {
        this.offerConfigs = offerConfigs;
    }

    public void setOfferExcludeConfigs(final Set<OfferExcludeConfig> offerExcludeConfigs) {
        this.offerExcludeConfigs = offerExcludeConfigs;
    }

    public void setSellingTag(final String sellingTag) {
        this.sellingTag = sellingTag;
    }

    public void setSeo(final Seo seo) {
        this.seo = seo;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    public void setSubCategoryAttributeses(final Set<SubCategoryAttributes> subCategoryAttributeses) {
        this.subCategoryAttributeses = subCategoryAttributeses;
    }

    public void setSubCategoryCode(final String subCategoryCode) {
        this.subCategoryCode = subCategoryCode;
    }

    public void setSubCategoryCount(final long subCategoryCount) {
        this.subCategoryCount = subCategoryCount;
    }

    public void setSubCategoryImageses(final Set<SubCategoryImages> subCategoryImageses) {
        this.subCategoryImageses = subCategoryImageses;
    }

    public void setSubCategoryName(final String subCategoryName) {
        this.subCategoryName = subCategoryName;
    }

    public void setSubCategoryTagses(final Set<SubCategoryTags> subCategoryTagses) {
        this.subCategoryTagses = subCategoryTagses;
    }

}
