package com.meat.domain;

// Generated Jan 11, 2016 12:46:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.*;

/**
 * SubOrderStatusCode generated by hbm2java
 */
@Entity
@Table(name = "sub_order_status_code", catalog = "meat_app")
public class SubOrderStatusCode extends AbstractDomain implements java.io.Serializable {

    private SubOrder subOrder;
    private String subOrderStatusName;
    private Date subOrderStatusDate;
    private String subOrderStatusDescription;

    public SubOrderStatusCode() {
    }

    public SubOrderStatusCode(final String id, final SubOrder subOrder, final String subOrderStatusName) {
        this.id = id;
        this.subOrder = subOrder;
        this.subOrderStatusName = subOrderStatusName;

    }

    public SubOrderStatusCode(final String id, final SubOrder subOrder, final String subOrderStatusName, final Date subOrderStatusDate,
            final String subOrderStatusDescription) {
        this.id = id;
        this.subOrder = subOrder;
        this.subOrderStatusName = subOrderStatusName;
        this.subOrderStatusDate = subOrderStatusDate;
        this.subOrderStatusDescription = subOrderStatusDescription;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sub_order_id", nullable = false)
    public SubOrder getSubOrder() {
        return subOrder;
    }

    /**
     * @return the subOrderStatusDate
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "sub_order_status_date", length = 19)
    public Date getSubOrderStatusDate() {
        return subOrderStatusDate;
    }

    /**
     * @return the subOrderStatusDescription
     */
    @Column(name = "sub_order_status_description")
    public String getSubOrderStatusDescription() {
        return subOrderStatusDescription;
    }

    @Column(name = "sub_order_status_name", nullable = false, length = 45)
    public String getSubOrderStatusName() {
        return subOrderStatusName;
    }

    public void setSubOrder(final SubOrder subOrder) {
        this.subOrder = subOrder;
    }

    /**
     * @param subOrderStatusDate
     *            the subOrderStatusDate to set
     */
    public void setSubOrderStatusDate(final Date subOrderStatusDate) {
        this.subOrderStatusDate = subOrderStatusDate;
    }

    /**
     * @param subOrderStatusDescription
     *            the subOrderStatusDescription to set
     */
    public void setSubOrderStatusDescription(final String subOrderStatusDescription) {
        this.subOrderStatusDescription = subOrderStatusDescription;
    }

    public void setSubOrderStatusName(final String subOrderStatusName) {
        this.subOrderStatusName = subOrderStatusName;
    }

}
