package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", catalog = "meat_app")
public class Tags extends AbstractDomain implements java.io.Serializable {

    private TagType tagType;
    private Seo seo;
    private String tagName;
    private String description;
    private Date createdDate;
    private String status;
    private Integer countFlag;
    private Set<CategoryTags> categoryTagses = new HashSet<CategoryTags>(0);
    private Set<ItemTags> itemTagses = new HashSet<ItemTags>(0);
    private Set<SubCategoryTags> subCategoryTagses = new HashSet<SubCategoryTags>(0);

    public Tags() {
    }

    public Tags(final String id, final TagType tagType, final Integer countFlag, final Seo seo, final String tagName,
            final Date createdDate) {
        this.id = id;
        this.tagType = tagType;
        this.seo = seo;
        this.tagName = tagName;
        this.countFlag = countFlag;
        this.createdDate = createdDate;
    }

    public Tags(final String id, final TagType tagType, final Seo seo, final String tagName, final String description,
            final Date createdDate, final String status, final Integer countFlag, final Set<CategoryTags> categoryTagses,
            final Set<ItemTags> itemTagses, final Set<SubCategoryTags> subCategoryTagses) {
        this.id = id;
        this.tagType = tagType;
        this.seo = seo;
        this.tagName = tagName;
        this.description = description;
        this.countFlag = countFlag;
        this.createdDate = createdDate;
        this.status = status;
        this.categoryTagses = categoryTagses;
        this.itemTagses = itemTagses;
        this.subCategoryTagses = subCategoryTagses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tags")
    public Set<CategoryTags> getCategoryTagses() {
        return categoryTagses;
    }

    @Column(name = "count_flag")
    public Integer getCountFlag() {
        return countFlag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", nullable = false, length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "description", length = 400)
    public String getDescription() {
        return description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tags")
    public Set<ItemTags> getItemTagses() {
        return itemTagses;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seo_id", nullable = false)
    public Seo getSeo() {
        return seo;
    }

    @Column(name = "status", length = 45)
    public String getStatus() {
        return status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tags")
    public Set<SubCategoryTags> getSubCategoryTagses() {
        return subCategoryTagses;
    }

    @Column(name = "tag_name", nullable = false, length = 45)
    public String getTagName() {
        return tagName;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tag_type_id", nullable = false)
    public TagType getTagType() {
        return tagType;
    }

    public void setCategoryTagses(final Set<CategoryTags> categoryTagses) {
        this.categoryTagses = categoryTagses;
    }

    public void setCountFlag(final Integer countFlag) {
        this.countFlag = countFlag;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setItemTagses(final Set<ItemTags> itemTagses) {
        this.itemTagses = itemTagses;
    }

    public void setSeo(final Seo seo) {
        this.seo = seo;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    public void setSubCategoryTagses(final Set<SubCategoryTags> subCategoryTagses) {
        this.subCategoryTagses = subCategoryTagses;
    }

    public void setTagName(final String tagName) {
        this.tagName = tagName;
    }

    public void setTagType(final TagType tagType) {
        this.tagType = tagType;
    }

}
