package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * TagType generated by hbm2java
 */
@Entity
@Table(name = "tag_type", catalog = "meat_app")
public class TagType extends AbstractDomain implements java.io.Serializable {

    private String tagTypeName;
    private String description;
    private Date createdDate;
    private String status;
    private Set<Tags> tagses = new HashSet<Tags>(0);

    public TagType() {
    }

    public TagType(final String id, final String tagTypeName, final Date createdDate, final String status) {
        this.id = id;
        this.tagTypeName = tagTypeName;
        this.createdDate = createdDate;
        this.status = status;
    }

    public TagType(final String id, final String tagTypeName, final String description, final Date createdDate, final String status,
            final Set<Tags> tagses) {
        this.id = id;
        this.tagTypeName = tagTypeName;
        this.description = description;
        this.createdDate = createdDate;
        this.status = status;
        this.tagses = tagses;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", nullable = false, length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "description", length = 400)
    public String getDescription() {
        return description;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tagType")
    public Set<Tags> getTagses() {
        return tagses;
    }

    @Column(name = "tag_type_name", nullable = false, length = 45)
    public String getTagTypeName() {
        return tagTypeName;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    public void setTagses(final Set<Tags> tagses) {
        this.tagses = tagses;
    }

    public void setTagTypeName(final String tagTypeName) {
        this.tagTypeName = tagTypeName;
    }

}
