package com.meat.domain;

// Generated Feb 13, 2016 10:49:53 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * UsersOffer generated by hbm2java
 */
@Entity
@Table(name = "users_offer", catalog = "meat_app")
public class UsersOffer extends AbstractDomain implements java.io.Serializable {

    private Users users;
    private Offer offer;
    private OfferConfig offerConfig;
    private String status;

    public UsersOffer() {
    }

    public UsersOffer(final String id, final Users users, final Offer offer, final OfferConfig offerConfig, final String status) {
        this.id = id;
        this.users = users;
        this.offer = offer;
        this.offerConfig = offerConfig;
        this.status = status;
    }

    public UsersOffer(final String id, final Users users, final String status) {
        this.id = id;
        this.users = users;
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "offer_id")
    public Offer getOffer() {
        return offer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "offer_config_id")
    public OfferConfig getOfferConfig() {
        return offerConfig;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id", nullable = false)
    public Users getUsers() {
        return users;
    }

    public void setOffer(final Offer offer) {
        this.offer = offer;
    }

    public void setOfferConfig(final OfferConfig offerConfig) {
        this.offerConfig = offerConfig;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    public void setUsers(final Users users) {
        this.users = users;
    }

}
