package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * SellerBranchAddress generated by hbm2java
 */
@Entity
@Table(name = "user_address", catalog = "meat_app")
public class UserAddress extends AbstractDomain implements java.io.Serializable {

    private Address address;
    private Users users;

    public UserAddress() {
    }

    public UserAddress(final Address address, final Users users) {

        this.address = address;
        this.users = users;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "address_id", nullable = false)
    public Address getAddress() {
        return address;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id", nullable = false)
    public Users getUsers() {
        return users;
    }

    public void setAddress(final Address address) {
        this.address = address;
    }

    public void setUsers(final Users users) {
        this.users = users;
    }

}
