package com.meat.domain;

// Generated Nov 4, 2015 12:01:05 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.*;

/**
 * UserSellerItemRating generated by hbm2java
 */
@Entity
@Table(name = "user_seller_item_rating", catalog = "meat_app")
public class UserSellerItemRating extends AbstractDomain implements java.io.Serializable {

    private SellerItem sellerItem;
    private Users users;
    private String description;
    private Date createdDate;
    private int rating;
    private String title;

    public UserSellerItemRating() {
    }

    public UserSellerItemRating(final String id, final SellerItem sellerItem, final Users users, final String description,
            final Date createdDate, final int rating, final String title) {
        this.id = id;
        this.sellerItem = sellerItem;
        this.users = users;
        this.description = description;
        this.createdDate = createdDate;
        this.rating = rating;
        this.title = title;
    }

    public UserSellerItemRating(final String id, final SellerItem sellerItem, final Users users, final String description,
            final int rating) {
        this.id = id;
        this.sellerItem = sellerItem;
        this.users = users;
        this.description = description;
        this.rating = rating;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "created_date", length = 10)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "description", nullable = false, length = 45)
    public String getDescription() {
        return description;
    }

    @Column(name = "rating", nullable = false)
    public int getRating() {
        return rating;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_item_id", nullable = false)
    public SellerItem getSellerItem() {
        return sellerItem;
    }

    /**
     * @return the title
     */
    @Column(name = "title")
    public String getTitle() {
        return title;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public Users getUsers() {
        return users;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setRating(final int rating) {
        this.rating = rating;
    }

    public void setSellerItem(final SellerItem sellerItem) {
        this.sellerItem = sellerItem;
    }

    /**
     * @param title
     *            the title to set
     */
    public void setTitle(final String title) {
        this.title = title;
    }

    public void setUsers(final Users users) {
        this.users = users;
    }

}
