package com.meat.domain;

// Generated Jan 11, 2016 12:46:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Zone generated by hbm2java
 */
@Entity
@Table(name = "zone", catalog = "meat_app")
public class Zone extends AbstractDomain implements java.io.Serializable {

    private String zoneName;
    private String status;
    private String description;
    private Date createdDate;
    private ZoneCity zoneCity;
    private Set<SellerBranchZone> sellerBranchZones = new HashSet<SellerBranchZone>(0);
    private Set<ZoneArea> zoneAreas = new HashSet<ZoneArea>(0);

    public Zone() {
    }

    public Zone(final String id, final String zoneName, final String status, final ZoneCity zoneCity) {
        this.id = id;
        this.zoneName = zoneName;
        this.status = status;
        this.zoneCity = zoneCity;
    }

    public Zone(final String id, final String zoneName, final ZoneCity zoneCity, final String status, final String description,
            final Date createdDate, final Set<ZoneArea> zoneAreas, final Set<SellerBranchZone> sellerBranchZones) {
        this.id = id;
        this.zoneName = zoneName;
        this.zoneCity = zoneCity;
        this.status = status;
        this.description = description;
        this.createdDate = createdDate;
        this.sellerBranchZones = sellerBranchZones;
        this.zoneAreas = zoneAreas;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @Column(name = "description", length = 200)
    public String getDescription() {
        return description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "zone")
    public Set<SellerBranchZone> getSellerBranchZones() {
        return sellerBranchZones;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    /**
     * @return the zoneAreas
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "zone")
    public Set<ZoneArea> getZoneAreas() {
        return zoneAreas;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "zone_city_id", nullable = false)
    public ZoneCity getZoneCity() {
        return zoneCity;
    }

    @Column(name = "zone_name", nullable = false, length = 45)
    public String getZoneName() {
        return zoneName;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setSellerBranchZones(final Set<SellerBranchZone> sellerBranchZones) {
        this.sellerBranchZones = sellerBranchZones;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    /**
     * @param zoneAreas
     *            the zoneAreas to set
     */
    public void setZoneAreas(final Set<ZoneArea> zoneAreas) {
        this.zoneAreas = zoneAreas;
    }

    public void setZoneCity(final ZoneCity zoneCity) {
        this.zoneCity = zoneCity;
    }

    public void setZoneName(final String zoneName) {
        this.zoneName = zoneName;
    }

}
